### ISSUE TITLE
Ability to query the public CVE-search instance and return vulnerabilities

### ISSUE THREAD

**Issue by tdruez** [nexB/vulnerablecode#1]
Given a `package identifier` input, return if there is a known vulnerability for it.

Package identifiers:
- name
- name+version

Behind the scenes:
1. Query the CVE-search API and try to find a match for the package 
2. Return results

Step 1. would after that be replaced by a local query, to the local db, where the aggregated and correlated vulnerability data would be populated from the scrapers, but let's not store anything for now, simply get the data on demand.

**Comment by pombredanne** [comment]
Merged. Closing
