### ISSUE TITLE
Registration form does not comply with UI standards

### ISSUE THREAD

**Issue by tdruez** [nexB/vulnerablecode#1002]
https://public.vulnerablecode.io/account/request_api_key/ looks quite bad and convey the wrong first impression, it needs to be upgraded to proper Bulma CSS, see https://bulma.io/documentation/form/general/

Also, “then visit the live OpenAPI documentation, and the API endpoint.” those 2 links are pointing to the same URL.

**Comment by TG1999** [comment]
![Screenshot from 2022-11-15 19-02-03](https://user-images.githubusercontent.com/34160672/201932159-ff8f4139-cd6a-49de-b9cb-22199999fa31.png)
@tdruez I have adjusted the UI using bulma CSS class, please let me know if should I adjust something more specific

**Comment by TG1999** [comment]
Fixed in #1004
