### ISSUE TITLE
Sending API key using the email template 

### ISSUE THREAD

**Issue by ziadhany** [nexB/vulnerablecode#1003]

**Comment by TG1999** [comment]
@ziadhany would you like to elaborate a little on this ?

**Comment by ziadhany** [comment]
we send API key using email with `text/plain`  content type , 
it will be nice if we have nice email template with `text/html` content type. like this : 
![image](https://user-images.githubusercontent.com/29133904/201949919-5b7699c3-c4ab-4b74-a3a1-67c6d0f5b044.png)

https://docs.djangoproject.com/en/4.1/topics/email/#send-mail

**Comment by TG1999** [comment]
@ziadhany thanks for raising this, I think we can close this now?
