### ISSUE TITLE
Add logging for packages and vulnerabilities

### ISSUE THREAD

**Issue by TG1999** [nexB/vulnerablecode#1007]
- [ ] Any change done on any package or vulnerability should be logged and should be shown on the UI as an activity on that entity.
- [ ] Add a log for each vulnerability with the data and advisory it has been formed, see also: https://github.com/nexB/vulnerablecode/pull/1027#discussion_r1056851561.

A log should have:
- action date
- actor (importer/ improver)
- object (package/vulnerability)
- supporting data (how object and actor are associated, source of the log for example: URL of the advisory)
- vulnerablecode version ( version of vulnerablecode that was used at that time )

In VCIO we have these kind of situations as of now that we want to log:
- Importing an Advisory into VCIO - We need to log when the advisory was actually published upstream for every vulnerability and by which data source we have imported that advisory into VCIO with the source URL.
- Package-Vulnerability relationship logs - If a package is affected by/fixing a vulnerability, we should log it on the package and vulnerability side with the date when this inference was drawn.

See related issues:
- https://github.com/nexB/vulnerablecode/issues/590
- https://github.com/nexB/vulnerablecode/issues/924
- https://github.com/nexB/vulnerablecode/issues/536

 
Reported by @pombredanne

**Comment by DennisClark** [comment]
refer to "activitypub" and "activitystream" for logging models

**Comment by TG1999** [comment]
Ater all discussion PR https://github.com/nexB/vulnerablecode/pull/1310 is ready for review now

**Comment by TG1999** [comment]
Making a follow-up issue for adding improver for the packages and vulnerabilities that were imported prior introducing changelog and closing this for now. https://github.com/nexB/vulnerablecode/issues/1388
