### ISSUE TITLE
Collect xen

### ISSUE THREAD

**Issue by pombredanne** [nexB/vulnerablecode#103]
https://xenbits.xen.org/xsa/

**Comment by Pushpit07** [comment]
What should be the format for data collection?

**Comment by Pushpit07** [comment]
I was writing a script to collect xen. Had a few questions in mind. What data needs to be specifically collected from https://xenbits.xen.org/xsa/ ? 

<img width="1440" alt="Screenshot 2021-05-05 at 10 00 59" src="https://user-images.githubusercontent.com/57194612/117097289-d7a4ee80-ad88-11eb-9576-9a8e539e6c7c.png">

Do we just collect the CVE column and advisory, or anything else too?

**Comment by Pushpit07** [comment]
@sbs2001 ping

**Comment by pombredanne** [comment]
@Pushpit07 is there a better way than to scrape HTML? may be another source for the same data?
I can read on the page 
> A JSON document listing advisories is also available. 
with a link to https://xenbits.xen.org/xsa/xsa.json which is a nicely structure JSON file

The file seems to contain everything the HTML does have. And this not trivial (there are various Package URLs we could infer for xen or linux for instance)

**Comment by Pushpit07** [comment]
Yes, this json seems nicely structured. We can use it directly to collect data.
Working on it

**Comment by Hritik14** [comment]
The work was partial, this needs to be refactored and migrated to importer improver structure
