### ISSUE TITLE
Collect CPEs

### ISSUE THREAD

**Issue by pombredanne** [nexB/vulnerablecode#110]
See https://nvd.nist.gov/products/cpe
We need also to define some rules to map these to Package URL when possible (not every CPE is a package though (eg. hardware, commercial products), so we can have NVD vulnerabilities with something that is impacted but without a package...

**Comment by sbs2001** [comment]
Just to have things for reference here is a repaste from gitter :

>  Shivam Sandbhor
> @sbs2001
> Mar 08 08:57
> 
> The cpes are pretty straightforward to work with, but I have some questions:
> 1.How to deal with cpe which denote vulnerable 'hardware'(you cant have purls for these right)?
> The approach I can think of regarding cpes for 'applications' is :
> 1.Make simple parser to interpret cpe format cpe:/ {part} : {vendor} : {product} : {version} : {update} : {edition} : {language}, this data contains all the data required to create a purl.
> 2.Now some cpes specify versions using ranges, which we can lookup from the dictionary available at https://nvd.nist.gov/vuln/data-feeds#cpeMatch
> 
> The folks at Intel's cve-bin-tool have already implemented this , take a look https://github.com/intel/cve-bin-tool/blob/2a47acefda90ec563d08d6428ed183a2cb8f0e94/cve_bin_tool/cvedb.py#L467
> Shivam Sandbhor
> @sbs2001
> Mar 08 18:02
> So the pain point is how do we get 'type' field for the purl from the cpe
> Haiko Schol
> @haikoschol
> Mar 08 20:51
> @sbs2001 i think NVD advisories about hardware and non-open source software is out of scope for vulnerablecode


To summarise the things preventing us from mapping cpes to purls are 

1. No way to determine the 'type' just from looking the cpe, 'type' is an essential field required to construct purl 
2. We can determine hardware cpes(and ignore them) , but what about the vulnerabilities affecting non-open source software, I can think of mitigating this by filtering the cpe's by their vendor's(eg ignore cpes with vendors apple,microsoft etc)
