### ISSUE TITLE
Not able to clone the project from git

### ISSUE THREAD

**Issue by PankajJaisu** [nexB/vulnerablecode#1125]
When I am trying clone the vulnearablecode repositery I am facing following issue.

error: invalid path 'vulnerabilities/tests/test_data/redhat/RHSA-2022:1437.json'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
![image](https://user-images.githubusercontent.com/68227785/218301958-7d7b781a-f507-417c-9ef9-3dfa5b2122bb.png)

**Comment by 35C4n0r** [comment]
@TG1999 @pombredanne this issue is occuring because of the Files which includes ":" in their filename, this is not valid in Windows. If possible we should refactor the filenames with their uses.

**Comment by rabajaj0509** [comment]
I would like to work on this issue.

**Comment by PankajJaisu** [comment]
@rabajaj0509 Should I close this issue?

**Comment by rabajaj0509** [comment]
Yes, we can close this one now.

**Comment by PankajJaisu** [comment]
ok Thanks! @rabajaj0509
