### ISSUE TITLE
Update documentation for v32

### ISSUE THREAD

**Issue by DennisClark** [nexB/vulnerablecode#1148]
Review existing documentation for correctness 
* installation instructions
* usage instructions
* API usage information 

make sure the Changelog is complete
are there any Upgrade instructions

**Comment by TG1999** [comment]
User-
- Using the UI and API
- Explain how to use API via openAPI documentation
- A Table to show endpoint what to query it with and what you can expect from the output. 
- Explain WebUI
  - Search by vulnerabilities and packages
  - PURL or fragment of PURL
  - Drill on details and all the thing shown on the package details page.

Developer - 
Move importer and improver to CONTRIBUTING section

Local Instance - 
- Installation
- API usage
