### ISSUE TITLE
License information not available

### ISSUE THREAD

**Issue by OliverFendt** [nexB/vulnerablecode#115]
There is no license available  - so I think the project cannot be used by anybody. Would it be possible that you define a license for the proiect - that others can use it. This would be great

**Comment by pombredanne** [comment]
@OliverFendt how shocking :scream:  sounds like a true cobbler's son problem! I will add the top level data ASAP.

That said, the code license is the same as Scancode and you can see it in the code proper https://github.com/nexB/vulnerablecode/blob/develop/vulnerablecode/urls.py

There is the issue of the data license that is not yet fully settled as explained here: https://github.com/nexB/vulnerablecode/issues/63 
In any case the overall data set license should be either CC0 or CC-BY TBD based on legal review and advice and hopefully that will be all that's needed.
