### ISSUE TITLE
Add CVE support in SnykDataSource

### ISSUE THREAD

**Issue by keshav-space** [nexB/vulnerablecode#1163]
Implement `datasource_advisory_from_cve` in SnykDataSource

For example, see `GithubDataSource.datasource_advisory_from_cve`:
https://github.com/nexB/vulnerablecode/blob/0a8f7a863de3062deabcb3cff347f64bee1e776e/vulntotal/datasources/github.py#L54-L73

**Comment by Pushpit07** [comment]
Hey, @keshav-space can I take this up?

**Comment by keshav-space** [comment]
> Hey @keshav-space, can I take this up?

Sure, go ahead.

**Comment by shravankshenoy** [comment]
Hey @keshav-space, while working on this issue, I found a minor bug in the datasource_advisory_from_cve function, for which I have created an issue (#1398) and pull request (#1399) as well

Coming to this issue, I think the code for Snyk will be slightly different from the Github one as for Github we use GraphQL to connect to Github API but for Snyk we would have to use BeautifulSoup (ofcourse other than that I think logic would be same). To add this feature, I am planning to follow the steps below

1. Go to the URL https://security.snyk.io/vuln?search={cve_id} and parse the HTML page
2. Loop through all vulnerabilities in the page and for each vulnerability parse the affected version and fixed version from the respective urls (which will be of the form https://security.snyk.io/vuln/{snyk_id})
3. Return the data as VendorData instance

I will try to write the code using the above steps. In the meanwhile, if there is anything I have missed, do let me know.

**Comment by keshav-space** [comment]
> Coming to this issue, I think the code for Snyk will be slightly different from the Github one as for Github we use GraphQL to connect to Github API but for Snyk we would have to use BeautifulSoup (ofcourse other than that I think logic would be same). To add this feature, I am planning to follow the steps below
> 
> 1. Go to the URL [https://security.snyk.io/vuln?search={cve_id}](https://security.snyk.io/vuln?search=%7Bcve_id%7D) and parse the HTML page
> 2. Loop through all vulnerabilities in the page and for each vulnerability parse the affected version and fixed version from the respective urls (which will be of the form [https://security.snyk.io/vuln/{snyk_id}](https://security.snyk.io/vuln/%7Bsnyk_id%7D))
> 3. Return the data as VendorData instance
> 
> I will try to write the code using the above steps. In the meanwhile, if there is anything I have missed, do let me know.

@shravankshenoy Sounds good to me 👍🏻

**Comment by shravankshenoy** [comment]
Hi everyone, I have raised a PR to add CVE support in Snyk data source. Let me know if any changes are required.
PR #1405
