### ISSUE TITLE
Vulnerability data should enter into database at import time

### ISSUE THREAD

**Issue by TG1999** [nexB/vulnerablecode#1198]
Currently, when we run any importer, only the advisory table is populated and we have to run the default improver to enter the imported advisory data into other tables, instead, we should enter all the imported advisories at that from a particular importer at the time of import itself.

**Comment by Hritik14** [comment]
Isn't handling of version constraints a job for improver and importer is supposed to only scrape data as it is from the internet?

**Comment by TG1999** [comment]
Completed in #1280
