### ISSUE TITLE
Missing quotes for href values in template

### ISSUE THREAD

**Issue by tdruez** [nexB/vulnerablecode#1217]
https://github.com/nexB/vulnerablecode/blob/main/vulnerabilities/templates/package_details.html#L69C48-L69C48
https://github.com/nexB/vulnerablecode/blob/main/vulnerabilities/templates/package_details.html#L116
https://github.com/nexB/vulnerablecode/blob/16af83f4b38e293e404417a51eee06f4b5819e57/vulnerabilities/templates/package_details.html#L69

**Comment by TG1999** [comment]
Fixed by #1222
