### ISSUE TITLE
Report only those fixed versions that are greater than the affected version

### ISSUE THREAD

**Issue by johnmhoran** [nexB/vulnerablecode#1228]
The VulnerableCode UI and API currently report a full set of all fixed versions of a package that are related directly or indirectly to a particular affected version, including fixed versions whose version number is less than the affected version number.  This seems potentially confusing to users and inaccurately identifies package versions that a user should consider to address an identified vulnerability.

It would be more useful (and accurate) if the VulnerableCode UI and API reported only those fixed versions that are greater than the particular affected version at issue.  I've attached a `.xlsx` file containing examples of fixed-version mismatches.  

See also
- https://github.com/nexB/vulnerablecode/issues/863
- https://github.com/nexB/vulnerablecode/issues/630

[examples-of-affected-vs-fixed-version-mismatches-v0.01.xlsx](https://github.com/nexB/vulnerablecode/files/11987221/examples-of-affected-vs-fixed-version-mismatches-v0.01.xlsx)

**Comment by DennisClark** [comment]
good idea

**Comment by johnmhoran** [comment]
My push is still a work-in-progress and retains many print statements for ongoing exploration of the data and functions.  The terminal displays some relevant high-level data about the affected package, the vulns and the fixing packages.

Working on the `Packages` class in `models.py`, I've created a function `get_fixing_packages(self)` in which `Prefetch` takes the list of vulns affecting the current package, retrieves a list of the fixing packages for each vuln, and assigns the result to a custom attribute, `filtered_fixed_packages`, that we can call when needed.

We also have the very beginnings of a function `assign_univers_version(self, fixing_pkg)`, which identifies which `univers` version applies to the two packages to be compared (`self` and a fixing package), evaluates whether the fixing_pkg version is > than the target affected package, and returns `True` or `False`.  I need to add more `univers` versions to the dictionary; and still need to check which fixing version is closest to (but greater than) the affected version.  

All of this is conveyed to the Jinja2 template (`package_details.html`) with this `context` key-value pair in the `PackageDetails` class in `views.py`: `context["get_fixing_packages"] = package.get_fixing_packages` -- called in the Jinja2 template with `{% if pkg in get_fixing_packages %}`.

I'm using some red and green colors in the Package details template to highlight the test data and have included a short explanation in the template for the time being.  These 4 example searches (all `maven` for now) illustrate the fixing packages we start with (red) and the filtering we do to match `type`, `namespace` etc. and discard "backport" versions (green).

pkg:maven/net.minidev/json-smart@2.3 
pkg:maven/org.apache.hadoop/hadoop-common@3.2.2 
pkg:maven/org.springframework/spring-webmvc@4.1.0 
pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.13.1

**Comment by pombredanne** [comment]
Here are some suggestion for your consideration:

- The "closest fixed by packages" should just be "Fixed by" IMHO. This is simpler and this is the concept exactly anyway, so no need to get "closest". The fact we have purl makes it obvious these are packages. Or we could even go as "Fixed by versions" and only list versions (and link to purls), to be discussed.

- "Vulnerabilities: 5 ?" may be more explicit as "Other vulnerabilities" or "Affected by 5 other vulnerabilities ?" 

- The text popup behind the :question: question mark may be better as "This version is affected by these other vulnerabilities:"

- "Closest non-vulnerable purl" may be better as simply "Non-vulnerable version", and were we would display only the version, yet link to the purl? (the API would get the purl)

- In the same way, "Latest non-vulnerable purl" may be better as "Latest non-vulnerable version", and were we would display only the version, yet link to the purl? (the API would get the purl too). Also we could consider the latest minor version (here some version 9.x) vs. the latest major version( here some version 10.x) separately, as packages with multiple version lines like Tomcat would benefit from this.

In general I feel avoiding the visual repetition of the purl everywhere when only the version changed would simplify the display.

Also what happens when:
- there is no other vulnerabilities?
- there is no package fixing a vulnerability?
- there is no latest vulnerable?

**Comment by pombredanne** [comment]
> I've changed all instances of PURL to purl.

I think this is something we need to decide and apply across all projects and docs uniformly. @adaaaam @DennisClark @mjherzog ... what's your take?
- PURL, purl, Purl, pURL?
- package URL, Package URL, package-url, Package-URL, package-URL?

**Comment by adaaaam** [comment]
i thought we previously agreed on Package-URL or PURL... we need to pick one and be consistent going forward.

**Comment by DennisClark** [comment]
I agree with Adam on this one: 
long-form: Package-URL
short-form: PURL

although, I am open to strong arguments in favor of purl for the short-form.

**Comment by mjherzog** [comment]
+1 for PURL and Package-URL; "purl" gets lost anytime you see it in a sentence. This is not like Package vs package where the core term is generic out in the world

**Comment by johnmhoran** [comment]
I've just committed and pushed my latest code to the open PR (https://github.com/nexB/vulnerablecode/pull/1249), with more work to do, starting with trying to replace my helper functions and related code with built-in `univers` capabilities.

All 7 checks passed, but I see an alert of a conflict in `vulnerabilities/tests/test_models.py`.  Looking at https://github.com/nexB/vulnerablecode/pull/1249/conflicts, it seems the following code has been added at the bottom of my new `class TestPackageModel(TestCase)`.

```
    def test_cwe_not_present_in_weaknesses_db(self):
        w1 = models.Weakness.objects.create(name="189")
        assert w1.weakness is None
        assert w1.name is ""
        assert w1.description is ""
```

That looks fine and I suppose I could just OK it using the GH editor, then do a pull from my branch to update the local version.

BUT: what is this and where did it come from?  I did not add it, and I see no record in the issue of the PR of some outside addition -- or maybe I'm missing that?  🤔

**Comment by johnmhoran** [comment]
Just committed and pushed my latest.  More to do including merging `main`.

**Comment by johnmhoran** [comment]
@pombredanne I just did another push of my latest, this time addressing your UI comments from last week:

The "closest fixed by packages" should just be "Fixed by" IMHO. This is simpler and this is the concept exactly anyway, so no need to get "closest". The fact we have purl makes it obvious these are packages. Or we could even go as "Fixed by versions" and only list versions (and link to purls), to be discussed.

- Agreed -- simpler/cleaner.  Changed to "Fixed by packages".  (I like the versions suggestions as well.)  If you meant "Fixed by" and no reference to "packages", let me know.

"Vulnerabilities: 5 ?" may be more explicit as "Other vulnerabilities" or "Affected by 5 other vulnerabilities ?"

- Good idea.  This now reads "Affected by [number] other vulnerability/vulnerabilities." -- the last term is chosen with a Jinja2 if/else (which also addresses 0 fixed_by and 0 other vulnerabilities permutations).

The text popup behind the ❓ question mark may be better as "This version is affected by these other vulnerabilities:"

- Agreed and done.

"Closest non-vulnerable purl" may be better as simply "Non-vulnerable version", and were we would display only the version, yet link to the purl? (the API would get the purl)

- Done.  I added version data to the dictionary returned by my new property method `fixed_package_details()` and refer to the version rather than the purl in the Package details page.  Definitely a cleaner/crisper display.

In the same way, "Latest non-vulnerable purl" may be better as "Latest non-vulnerable version", and were we would display only the version, yet link to the purl? (the API would get the purl too). 

- Done.  

Also we could consider the latest minor version (here some version 9.x) vs. the latest major version( here some version 10.x) separately, as packages with multiple version lines like Tomcat would benefit from this.

- Not sure what you have in mind -- a discussion and/or examples would help flesh this out.

In general I feel avoiding the visual repetition of the purl everywhere when only the version changed would simplify the display.

- Agreed -- it's a noticeable improvement.

Also what happens when:

there is no other vulnerabilities?
there is no package fixing a vulnerability?
there is no latest vulnerable?

- If I understand your questions, these screen shots should answer them.  The permutations are moderately involved and I might have missed some of them.  Please let me know if that's not the case or if you have more questions/suggestions (heartily encouraged).

![image](https://github.com/nexB/vulnerablecode/assets/11096678/276c7003-6807-44a7-bb65-42a25724c157)

![image](https://github.com/nexB/vulnerablecode/assets/11096678/76992ed7-c1e0-4d5d-acb3-9548b017cff7)

![image](https://github.com/nexB/vulnerablecode/assets/11096678/6526694d-0075-4dc5-b10c-a0f1129204f6)

**Comment by pombredanne** [comment]
@johnmhoran Thanks!

>> Also we could consider the latest minor version (here some version 9.x) vs. the latest major version( here some version 10.x) separately, as packages with multiple version lines like Tomcat would benefit from this.

> Not sure what you have in mind -- a discussion and/or examples would help flesh this out.

- Say I have a vulnerability that affects Tomcat 9.3.0 and 10.4.1 that is fixed by 9.4.2 and 10.5.2. 
- Say that further we have the latest versions in each version line to be 9.6.7 and 10.8.2 that are also non vulnerable

Here for 9.3.0:
- the closest non-vulnerable is 9.4.2 
- the latest non-vulnerable for 9.6.7
And for 10.4.1:
- the closest non-vulnerable is 10.5.2
- the latest non-vulnerable for 10.8.2

The idea is to treat the "major" version ranges (e.g., 9 and 10) almost as if they were different packages.

**Comment by johnmhoran** [comment]
Here's an example of the `Package details` page with clearer (but slightly longer) section headings replacing `Affected by vulnerabilities` and `Fixed by vulnerabilities`.  Subject to comments, I'll include this in my next push (I have some refactoring to do) -- and look forward to comments/suggestions on the UI and dictionary changes I pushed yesterday.

![image](https://github.com/nexB/vulnerablecode/assets/11096678/974e234f-5f0d-4332-a684-153273a76ead)

**Comment by johnmhoran** [comment]
Here is an example of the possible permutations (created as I've been rewriting the dictionary):

![image](https://github.com/nexB/vulnerablecode/assets/11096678/4489148a-586a-4c94-ac1d-92c4577c1926)

**Comment by johnmhoran** [comment]
@pombredanne @TG1999 @DennisClark  Here's the latest dictionary structure re package vulnerabilities:

```
{
    "purl": "pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.13.1",
    "vulnerabilities": [
        {
            "vulnerability": "VCID-2nyb-8rwu-aaag",
            "closest_fixed_by": {
                "purl": "pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.13.2",
                "type": "maven",
                "namespace": "com.fasterxml.jackson.core",
                "name": "jackson-databind",
                "version": "2.13.2",
                "qualifiers": {},
                "subpath": ""
            },
            "closest_fixed_by_vulnerabilities": [
                {
                    "vuln_id": "VCID-gqhw-ngh8-aaap"
                },
                {
                    "vuln_id": "VCID-t7e4-g3fr-aaan"
                }
            ]
        },
        {
            "vulnerability": "VCID-gqhw-ngh8-aaap",
            "closest_fixed_by": {
                "purl": "pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.13.4",
                "type": "maven",
                "namespace": "com.fasterxml.jackson.core",
                "name": "jackson-databind",
                "version": "2.13.4",
                "qualifiers": {},
                "subpath": ""
            },
            "closest_fixed_by_vulnerabilities": [
                {
                    "vuln_id": "VCID-t7e4-g3fr-aaan"
                }
            ]
        },
        {
            "vulnerability": "VCID-t7e4-g3fr-aaan",
            "closest_fixed_by": {
                "purl": "pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.14.0-rc1",
                "type": "maven",
                "namespace": "com.fasterxml.jackson.core",
                "name": "jackson-databind",
                "version": "2.14.0-rc1",
                "qualifiers": {},
                "subpath": ""
            },
            "closest_fixed_by_vulnerabilities": []
        }
    ],
    "closest_non_vulnerable": {
        "purl": "pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.14.0-rc1",
        "type": "maven",
        "namespace": "com.fasterxml.jackson.core",
        "name": "jackson-databind",
        "version": "2.14.0-rc1",
        "qualifiers": {},
        "subpath": ""
    },
    "latest_non_vulnerable": {
        "purl": "pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.14.0-rc1",
        "type": "maven",
        "namespace": "com.fasterxml.jackson.core",
        "name": "jackson-databind",
        "version": "2.14.0-rc1",
        "qualifiers": {},
        "subpath": ""
    }
}
```

**Comment by pombredanne** [comment]
May be we can find a way to avoid some name ambiguities (like in "closest_fixed_by_vulnerabilities" that seems to tell a vulnerability is fixing something) and avoid repetitions with something like this instead:
```Python
{
    "purl": "pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.13.1",
    "affected_by_vulnerabilities": [
        {
            "vulnerability": "VCID-2nyb-8rwu-aaag",
            "fixed_by_version": "2.13.2",
            "fixed_by_purl": "pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.13.2",
            "affected_by_other_vulnerabilities": [
                "VCID-gqhw-ngh8-aaap",
                "VCID-t7e4-g3fr-aaan",
            ]
        },
        {
            "vulnerability": "VCID-gqhw-ngh8-aaap",
            "fixed_by_version": "2.13.4",
            "fixed_by_purl": "pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.13.4",
            "affected_by_other_vulnerabilities": [
                "VCID-t7e4-g3fr-aaan"
            ]
        },
        {
            "vulnerability": "VCID-t7e4-g3fr-aaan",
            "fixed_by_version": "2.14.0-rc1",
            "fixed_by_purl": "pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.14.0-rc1",
            "affected_by_other_vulnerabilities": []
        }
    ],
    "closest_non_vulnerable_version": "2.14.0-rc1",
    "closest_non_vulnerable_purl": "pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.14.0-rc1",
    "latest__non_vulnerable_version": "2.14.0-rc1",
    "latest_non_vulnerable_purl": "pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.14.0-rc1",
}

```
Note also that since you use this in a template you could very much pass PackageURL objects instead of version and PURL strings: this would be as or more expressive and leaner. 
And the `purl.version` would available in the template.
```Python
{
    "purl": PackageURL.fomr_string("pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.13.1"),
    "affected_by_vulnerabilities": [
        {
            "vulnerability": "VCID-2nyb-8rwu-aaag",
            "fixed_by_purl": PackageURL.fomr_string("pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.13.2"),
            "affected_by_other_vulnerabilities": [
                "VCID-gqhw-ngh8-aaap",
                "VCID-t7e4-g3fr-aaan",
            ]
        },
        {
            "vulnerability": "VCID-gqhw-ngh8-aaap",
            "fixed_by_purl": PackageURL.fomr_string("pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.13.4"),
            "affected_by_other_vulnerabilities": [
                "VCID-t7e4-g3fr-aaan"
            ]
        },
        {
            "vulnerability": "VCID-t7e4-g3fr-aaan",
            "fixed_by_purl": PackageURL.fomr_string("pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.14.0-rc1"),
            "affected_by_other_vulnerabilities": []
        }
    ],
    "closest_non_vulnerable_purl": PackageURL.fomr_string("pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.14.0-rc1"),
    "latest_non_vulnerable_purl": PackageURL.fomr_string("pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.14.0-rc1"),
}
```
And here, each "vulnerability" item could also be a Vulnerability object that you must have used to create this data. Also I created the PURLs from string, but your code may have access to the object directly instead.

**Comment by johnmhoran** [comment]
Thanks for the suggestions @pombredanne .  Several days ago I actually tried something like this before I switched to the current approach.  I'll have to see if I recorded that effort in my notes, but the result -- I might have been trying to use a `vulnerabilities.Package` object as the value in the dict -- was a series of `not JSON serializable` errors.  I likely was not using the correct syntax/grammar.

I look forward to trying this approach.

**Comment by pombredanne** [comment]
Why do you need to serialize to JSON for the template use?

**Comment by johnmhoran** [comment]
I was passing the object as a value in the dictionary key-value pair.  That was the error I got.

**Comment by johnmhoran** [comment]
Looking at my notes, I think I tried

dict_vuln["closest_fixed_by_purl"] = str(closest_fixed_package)

where closest_fixed_package was the 0 index in a list of Packages.  A print statement gave me

`type(closest_fixed_package) = <class 'vulnerabilities.models.Package'>`

**Comment by johnmhoran** [comment]
I would like to finalize the structure and naming of the dictionary asap -- each time I need to make a change in the dict per suggestions (often key names), I spend more time than I'd prefer vetting and changing the Jinja2 template.

**Comment by johnmhoran** [comment]
@pombredanne Thanks again for the suggestion re how to add an object as the value of a dict key-value pair.  I think I may have the start of a cleaner and more useful dictionary....

**Comment by johnmhoran** [comment]
I also prefer `PURL` (and `Package-URL`), but note the refernces to `purl` not `PURL` throughout, e.g., https://github.com/package-url/purl-spec and https://github.com/package-url/purl-spec/blob/master/PURL-SPECIFICATION.rst.  (These pages also refer repeatedly to `package URL`.)

**Comment by johnmhoran** [comment]
Re identifying and comparing major versions of affected vs. fixed packages, see [the new issue in the univers repo](https://github.com/nexB/univers/issues/114).

**Comment by johnmhoran** [comment]
@pombredanne Following up on our discussion during today's jit.si meeting, am I correct in thinking that in this example -- where the only fixed and non-vulnerable versions for `pkg:pypi/setuptools@40.8.0` are all `pkg:pypi/setuptools@65.5.1` -- we want the updated Package details page to show an empty cell for `Non-vulnerable version`, `Latest non-vulnerable version` and `Fixed by`, since that version is a higher, i.e., breaking, version?

![image](https://github.com/nexB/vulnerablecode/assets/11096678/59204681-b86d-4dec-b8db-9ed3ebf146e5)

**Comment by johnmhoran** [comment]
I was just exploring the new issue @TG1999 opened, https://github.com/nexB/vulnerablecode/issues/1286, and I noticed that working in my 1228 branch, when I visit a Vulnerability details page and click one of the links in the `Fixed by packages` tab or the `Affected packages` tab, I get an error, e.g.,

```
Internal Server Error: /packages/pkg:apache/tomcat@10.0.0.0-M1
Traceback (most recent call last):
  File "/home/jmh/dev/nexb/vulnerablecode/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/jmh/dev/nexb/vulnerablecode/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/jmh/dev/nexb/vulnerablecode/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/jmh/dev/nexb/vulnerablecode/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/jmh/dev/nexb/vulnerablecode/venv/lib/python3.8/site-packages/django/views/generic/detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
  File "/home/jmh/dev/nexb/vulnerablecode/vulnerabilities/views.py", line 86, in get_context_data
    context["fixed_package_details"] = package.fixed_package_details
  File "/home/jmh/dev/nexb/vulnerablecode/vulnerabilities/models.py", line 857, in fixed_package_details
    closest_non_vulnerable_sib.purl
AttributeError: 'str' object has no attribute 'purl'

```

This is undoubtedly related to my revamping of the way the data is delivered to the Jinja2 template and is a reminder that the current Package details work will also require modifying the Vulnerability details template and likely the related models.py code and the views.py context as well.

**Comment by johnmhoran** [comment]
I think I've fixed the above error with minimal effort.  🤞

**Comment by johnmhoran** [comment]
@pombredanne @mjherzog @DennisClark @TG1999 @Hritik14 I have a question for you re how we want to represent the absence of data for certain fields in the `Package details` page.  My preference is to leave the value blank and say nothing at all.

There are at least 4 fields that raise this issue: 

- `Non-vulnerable version` -- if there is no responsive data, this can simply be empty, or can include a statement like `no reported data`.  We currently leave this blank if there is no such version.

- `Latest non-vulnerable version` -- same as above

- The `Fixed by` column in the `Vulnerabilities affecting this package` table:

  - If there is no responsive data, we currently say `There are no reported fixed versions.`
  - If there is a fixed-by version, we include the version (and a link to the relevant page), and in that column the version is followed by either the number of vulnerabilities for that fixed-by version (and a dropdown listing links) OR if no responsive data, we currently have `Affected by 0 other vulnerabilities.` with a green background.

I vote for a consistent treatment: no responsive data results in no statement of any sort -- just a blank cell.

Please share your thoughts and questions on this issue.

**Comment by DennisClark** [comment]
@johnmhoran   thanks for the detailed analysis.  `I vote for a consistent treatment: no responsive data results in no statement of any sort -- just a blank cell.`

**Comment by johnmhoran** [comment]
@AyanSinhaMahapatra @keshav-space @ziadhany My apologies for not including you in the above comment asking how we should represent the absence of data -- some sort of affirmative statement (e.g., "There is no responsive data" or "There is no fixing package version") vs. a simple blank table cell.  

Please share your thoughts and comments on this when you have a chance.  

FWIW, my general thinking is that we want to do our best to ensure that the user's interpretation of our data (or lack of responsive data) is precisely what we are trying to convey, and no more than that.  Put another way, saying that the DB contains no data re a package that fixes a particular vulnerability is not the same as asserting that there are no packages that fix that vulnerability.  OTOH, a blank cell means the DB has no responsive data, period, full stop.  But that's just my opinion, and there may be a better approach.

**Comment by ziadhany** [comment]
@johnmhoran It's okay. I know you didn't mean to
I vote for a consistent treatment: no responsive data results in no statement of any sort -- just a blank cell or simple try to hide this cell

**Comment by johnmhoran** [comment]
Thank you @ziadhany .  🙂

**Comment by johnmhoran** [comment]
@TG1999 FYI, I'm back working in my branch `1228-fixed-affected-version-matching`, updating and refactoring the Package-related tests in my new section `TestPackageModel(TestCase)`.  All 5 of the current tests pass (but need some serious TLC).  

However, when I run the whole test protocol `pytest -vs vulnerabilities/tests/test_models.py` we get 6 failures, all of them in vulnerability-related tests that predate my work.  I expect I'll address these failures when I turn to the vulnerability-related work down the road but thought you should be aware of these failures (which presumably also fail when the test suite is run in any branch, and I can confirm these fail when run in `main`).

```
FAILED vulnerabilities/tests/test_models.py::TestVulnerabilityModel::test_vulnerability_save_without_vulnerability_id - AssertionError: assert 0 == 1
FAILED vulnerabilities/tests/test_models.py::TestPackageRelatedVulnerablity::test_package_to_vulnerability - TypeError: PackageRelatedVulnerability() got unexpected keyword arguments: 'patched_package'
FAILED vulnerabilities/tests/test_models.py::TestPackageRelatedVulnerablity::test_vulnerability_package - TypeError: PackageRelatedVulnerability() got unexpected keyword arguments: 'patched_package'
FAILED vulnerabilities/tests/test_models.py::TestVulnerabilityModel::test_cwe_not_present_in_weaknesses_db - AttributeError: can't set attribute
FAILED vulnerabilities/tests/test_models.py::TestVulnerabilityModel::test_generate_vulcoid - AttributeError: type object 'Vulnerability' has no attribute 'generate_vulcoid'
FAILED vulnerabilities/tests/test_models.py::TestVulnerabilityModel::test_generate_vulcoid_given_timestamp_object - AttributeError: type object 'Vulnerability' has no attribute 'generate_vulcoid'
```

**Comment by johnmhoran** [comment]
@TG1999 Interesting -- in `main`, when I run `pytest -vs vulnerabilities/tests/test_models.py` I get these 6 failures, but when I run `make test` in `main` I get `299 passed, 1 skipped, 1 deselected, 6 warnings`.

**Comment by johnmhoran** [comment]
@pombredanne @TG1999 Subject to your feedback, I've finished my work on the package details template and code including the Package class, and have refactored my earlier -- and created new -- package-related tests.  Just committed and pushed and al checks passed.  See https://github.com/nexB/vulnerablecode/pull/1249

Re the tests in `test_models.py`, there are three classes.  The first two (`TestVulnerabilityModel()` and `TestPackageRelatedVulnerablity()`) are related to vulnerabilities, appear to have been created several years ago before substantial data structure changes took place, and contain tests that fail.  I think I should defer working on them until I tackle my vulnerability task (which will follow the Package API work coming up next).  Please let me know what you think.

The third test class is `TestPackageModel()`.  That's all new.

**Comment by johnmhoran** [comment]
@pombredanne  Here's a brief status report re my preliminary work on the Package API.

- Using a number of package examples, I've taken the existing Package API and added key/value pairs for the two types of non-vulnerable versions, e.g.,

```
            "next_non_vulnerable_version": "2.1.1",
            "latest_non_vulnerable_version": "2.1.1"
```

- Working inside the existing `"affected_by_vulnerabilities": []` list, which already has a nested `fixed_packages` list, I've started with this

```
                    "fixed_packages": [
                        {
                            "url": "http://public.vulnerablecode.io/api/packages/137159",
                            "purl": "pkg:npm/merge@1.2.1",
                            "is_vulnerable": true
                        }
                    ],
```

and updated it to include info about any fixed package's own vulnerabilities as well as purls that fix those nested vulnerabilities, like this

```
                    "fixed_packages": [
                        {
                            "url": "http://127.0.0.1:8001/api/packages/137159",
                            "purl": "pkg:npm/merge@1.2.1",
                            "is_vulnerable": true,
                            "affected_by_vulnerabilities": [
                                {
                                    "vulnerability": "VCID-rntr-ve3f-aaar",
                                    "fixed_by_purl": "pkg:npm/merge@2.1.1",
                                    "fixed_by_purl_vulnerabilities": []
                                }
                            ]
                        }
                    ],

```

I'm attaching a Word document comprising a 2-column table: Before (from the public VCIO API) and After (my local VCIO API this afternoon), for 2 packages: `pkg:pypi/redis@4.1.1` and `pkg:npm/merge@1.1.0`.  I've also experimented with other packages but focused on these 2 because the API output for the others is huge, often 40 pages or much more, and thus too unwieldy to work with.

As is my wont, the data in the tables has some color highlighting to focus on the relevant comparative passages, with green in the right (After) column showing what I've added.

This does not yet have a separate key/value pair pulling out the closest fixed by version for each vulnerability, and I'll turn to that next -- but what we already have inside the pre-existing `fixed_packages` field might be sufficient -- though these 2 examples don't reflect it, it seems that where there are multiple fixed packages for a vuln, the API already includes them all.  Here's an excerpt from one of my favorites, jackson-databind 2.13.1

```
                   "fixed_packages": [
                        {
                            "url": "http://127.0.0.1:8001/api/packages/124802",
                            "purl": "pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.12.6.1",
                            "is_vulnerable": true,
                            "affected_by_vulnerabilities": [
                                {
                                    "vulnerability": "VCID-gqhw-ngh8-aaap",
                                    "fixed_by_purl": "pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.13.4",
                                    "fixed_by_purl_vulnerabilities": [
                                        "VCID-t7e4-g3fr-aaan"
                                    ]
                                },
                                {
                                    "vulnerability": "VCID-t7e4-g3fr-aaan",
                                    "fixed_by_purl": "pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.14.0-rc1",
                                    "fixed_by_purl_vulnerabilities": []
                                }
                            ]
                        },
                        {
                            "url": "http://127.0.0.1:8001/api/packages/211533",
                            "purl": "pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.13.2",
                            "is_vulnerable": true,
                            "affected_by_vulnerabilities": [
                               {
                                    "vulnerability": "VCID-gqhw-ngh8-aaap",
                                    "fixed_by_purl": "pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.13.4",
                                    "fixed_by_purl_vulnerabilities": [
                                        "VCID-t7e4-g3fr-aaan"
                                    ]
                                },
                                {
                                    "vulnerability": "VCID-t7e4-g3fr-aaan",
                                    "fixed_by_purl": "pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.14.0-rc1",
                                    "fixed_by_purl_vulnerabilities": []
                                }
                            ]
                        },
                        {
                            "url": "http://127.0.0.1:8001/api/packages/124806",
                            "purl": "pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.13.2.1",
                            "is_vulnerable": true,
                            "affected_by_vulnerabilities": [
                                {
                                    "vulnerability": "VCID-gqhw-ngh8-aaap",
                                    "fixed_by_purl": "pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.13.4",
                                    "fixed_by_purl_vulnerabilities": [
                                        "VCID-t7e4-g3fr-aaan"
                                    ]
                                },
                                {
                                    "vulnerability": "VCID-t7e4-g3fr-aaan",
                                    "fixed_by_purl": "pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.14.0-rc1",
                                    "fixed_by_purl_vulnerabilities": []
                                }
                            ]
                        }
                    ],
```

[vcio-package-api-comparison-2023-09-13.docx](https://github.com/nexB/vulnerablecode/files/12602693/vcio-package-api-comparison-2023-09-13.docx)

**Comment by johnmhoran** [comment]
Here's the .docx.

[vcio-package-api-comparison-2023-09-13.docx](https://github.com/nexB/vulnerablecode/files/12602758/vcio-package-api-comparison-2023-09-13.docx)

**Comment by johnmhoran** [comment]
Here is an example of the latest Package details UI (as of just now), now displaying all `fixed by` versions in the `Fixed by` column -- our updated goal is to have the UI and API display the same data, no more and no less.

![image](https://github.com/nexB/vulnerablecode/assets/11096678/f6a755da-9998-473c-933f-8fbfeecfccaf)

**Comment by johnmhoran** [comment]
This is the corresponding portion of the Package API (still a work in progress) for the first of the two vulnerabilities shown in the UI above:

```
                    "fixed_packages": [
                        {
                            "url": "http://127.0.0.1:8001/api/packages/596462",
                            "purl": "pkg:pypi/redis@4.3.6",
                            "affected_by_vulnerabilities": [
                                {
                                    "vulnerability": "VCID-rqe1-dkmg-aaad"
                                }
                            ]
                        },
                        {
                            "url": "http://127.0.0.1:8001/api/packages/596466",
                            "purl": "pkg:pypi/redis@4.4.3",
                            "affected_by_vulnerabilities": [
                                {
                                    "vulnerability": "VCID-rqe1-dkmg-aaad"
                                }
                            ]
                        },
                        {
                            "url": "http://127.0.0.1:8001/api/packages/596369",
                            "purl": "pkg:pypi/redis@4.5.3",
                            "affected_by_vulnerabilities": [
                                {
                                    "vulnerability": "VCID-rqe1-dkmg-aaad"
                                }
                            ]
                        }
                    ],
```

**Comment by johnmhoran** [comment]
Another issue 1228 Package UI before/after:

![image](https://github.com/nexB/vulnerablecode/assets/11096678/4ba23300-38fd-484b-8002-91369c265398)

![image](https://github.com/nexB/vulnerablecode/assets/11096678/63d9be71-2eb2-44bb-8b15-c80d046e66d5)

**Comment by johnmhoran** [comment]
@pombredanne I see that the existing code for the Package API includes `fixed packages` (called `fixed by` in the UI) that are lesser versions than the searched-for package.  In the Package details UI, we don't include such versions.  

You've said we want the UI and API to return/display the same data -- do you agree that I should omit the lesser version(s) from the Package API `fixed packages` field?

**Comment by johnmhoran** [comment]
The issue re the lesser versions also raises questions like 

- if we have data identifying a version as fixing a vulnerability, do we really want to not make that data available in the UI and/or the API?
- is all of the data we have re fixed by versions correct?  For example, we recently saw some fixed version data involving several versions that shared the same minor version, if memory serves, which some might think illogical.

I don't mean to slow down this issue's progress with irrelevant questions, but do want to raise these just in case they're relevant and need to be considered now.

**Comment by TG1999** [comment]
@johnmhoran thanks! done in #1249
