### ISSUE TITLE
Ensure that we have updated data

### ISSUE THREAD

**Issue by pombredanne** [nexB/vulnerablecode#1270]
I would like to ensure that a CVE can be seen in VCIO ins less than a day.
Also I would like to have date and time data displayed in the UI and API so I know when things were last updated. This could be reported by data source or by package or vulnerability.

**Comment by nikkuAg** [comment]
is this issue still open?

**Comment by pombredanne** [comment]
@nikkuAg re:
> is this issue still open?
this is already being worked on... sorry for the late reply!

**Comment by TG1999** [comment]
@pombredanne 
Re:
> I would like to ensure that a CVE can be seen in VCIO ins less than a day.

See issue https://github.com/nexB/vulnerablecode/issues/1198 for this part which is now completed in https://github.com/nexB/vulnerablecode/pull/1280

The part for last updated date in UI and API is separately tracked in https://github.com/nexB/vulnerablecode/issues/924 feel free to close this if it makes sense.

**Comment by pombredanne** [comment]
@TG1999 Thanks... closing then now!
