### ISSUE TITLE
Input PURL does not match output PURL

### ISSUE THREAD

**Issue by johnmhoran** [nexB/vulnerablecode#1274]
Using the Package API to check for PURLs that are present and might have vulnerabilities, I discovered that for some PURLs like `pkg:deb/`, the actual correct name requires the `debian` namespace, which is missing.

**Comment by pombredanne** [comment]
@nikkuAg I think it is... @johnmhoran @TG1999 any input? Anyone working on this already?

**Comment by TG1999** [comment]
@nikkuAg you are welcome to work on this.

**Comment by nikkuAg** [comment]
Could you please explain this issue?

**Comment by mjherzog** [comment]
VulnerableCode already uses/provides the package namespace correctly so there is nothing to fix here. The work is needed in SCTK - https://github.com/nexB/scancode-toolkit/issues/3443
