### ISSUE TITLE
Bug in text for summary section

### ISSUE THREAD

**Issue by TG1999** [nexB/vulnerablecode#1279]
![Screenshot from 2023-08-28 15-13-37](https://github.com/nexB/vulnerablecode/assets/34160672/227e8006-53aa-4621-a8be-691bfcb409fe)

**Comment by johnmhoran** [comment]
Good catch @TG1999 -- thank you.  I'll take care of this.  👍

**Comment by TG1999** [comment]
Fixed by #1282
