### ISSUE TITLE
Enhance the VCIO UI to make use of all available screen space

### ISSUE THREAD

**Issue by DennisClark** [nexB/vulnerablecode#1299]
It is time to enhance the VCIO UI to be more flexible and make use of all available screen space.  (This should be done in all AboutCode.org projects.)

**Comment by johnmhoran** [comment]
A related consideration is responsive design, including an issue that came up yesterday while I was working on [issue 1228](https://github.com/nexB/vulnerablecode/issues/1228) -- we appear to have nearly 3000 instances of `px` (I'm the culprit) that will need to be converted to `rem` (in `custom.css` and mostly as width settings in a number of Jinja2 templates).

(I'm hoping there is some way we can automate the conversion process -- which might consist of dividing each `px` by 16 if 16px is our default font size and rounding in some manner, and of course agreeing to the number of decimal places for each resulting `rem`. ;-)

**Comment by johnmhoran** [comment]
Note that [the `bulma-0.9.4.min.css` used in SCIO](https://raw.githubusercontent.com/nexB/scancode.io/main/scancodeio/static/bulma-0.9.4.min.css) has 564 instances of `px` and 514 of `rem`.  The [bulma.css we use in VCIO](https://raw.githubusercontent.com/nexB/vulnerablecode/main/vulnerablecode/static/css/bulma.css) has a similar number of instances.

**Comment by johnmhoran** [comment]
@DennisClark @pombredanne and colleagues:  I've just increased the CSS width settings to use the same width as ScanCode.io and will push the changes and open a PR shortly.  This is VCIO before:

![image](https://github.com/nexB/vulnerablecode/assets/11096678/15d5c0bd-77be-4bb7-b06c-3b8c21480518)

and after:

![image](https://github.com/nexB/vulnerablecode/assets/11096678/443a2a96-3762-4338-922a-a81c36f206cd)

and this is the current ScanCode.io:

![image](https://github.com/nexB/vulnerablecode/assets/11096678/f290ddb1-d30e-4348-b49d-2012d7addbb4)
