### ISSUE TITLE
"fixing" or "fixed" -- how should we name a package that fixes a vulnerability?

### ISSUE THREAD

**Issue by johnmhoran** [nexB/vulnerablecode#1301]
A serious question.  Please do contribute your thoughts.  We will discuss on the next weekly jit.si.

- A vulnerability is "fixed by" a package.
- A vulnerability is "affecting" a package.
- A package is "fixing" a vulnerability.
- A package is "affected by" a vulnerability.

This is what we suggest after a discussion with @pombredanne .

TODO:

- Check the words used by NVD, GHSA, OSV et al./etc.

**Comment by mjherzog** [comment]
and check CycloneDX and SPDX (not sure if they have anything but they document many relationship pairs)

**Comment by johnmhoran** [comment]
Thank you @mjherzog -- I'll do that.

**Comment by mjherzog** [comment]
It seems that the affect/fix terminology is well-established. I recommend slight changes in wording as follows:

- A vulnerability is "fixed by" a package.
- A vulnerability "affects" a package.
- A package "fixes" a vulnerability.
- A package is "affected by" a vulnerability.

**Comment by DennisClark** [comment]
I second the recommendation

**Comment by johnmhoran** [comment]
I will paste some screen shots here in a little while illustrating our decision at today's jit.si meeting to keep the naming as it is and has been for a while on my issue #1228 VCIO UI.

**Comment by johnmhoran** [comment]
Some representative examples.  @DennisClark you'll like this first one.  ;-)

![image](https://github.com/nexB/vulnerablecode/assets/11096678/8c06b11a-f813-49af-a406-df189e01bab6)

**Comment by johnmhoran** [comment]
![image](https://github.com/nexB/vulnerablecode/assets/11096678/16439226-fc27-4a48-a61c-79e9410439cc)

**Comment by johnmhoran** [comment]
![image](https://github.com/nexB/vulnerablecode/assets/11096678/84601c1e-8785-4092-8f73-aeae1d4f60f1)

**Comment by johnmhoran** [comment]
![image](https://github.com/nexB/vulnerablecode/assets/11096678/a91a0f71-e599-4793-88c0-f43f87e7ee56)

**Comment by johnmhoran** [comment]
![image](https://github.com/nexB/vulnerablecode/assets/11096678/13f52cf5-319d-45af-b301-2bf58978016a)

**Comment by johnmhoran** [comment]
![image](https://github.com/nexB/vulnerablecode/assets/11096678/1b653ab3-e761-4617-86e7-70a47a27b5e9)

**Comment by johnmhoran** [comment]
I'm done.

**Comment by DennisClark** [comment]
@johnmhoran   thanks for the concrete examples.  I think that they illustrate the best approach to take.

**Comment by pombredanne** [comment]
Closed in favor of https://github.com/nexB/vulnerablecode/issues/1520
