### ISSUE TITLE
high memory consumption - vulnerabilities.improvers.default.DefaultImprover

### ISSUE THREAD

**Issue by turambarturin** [nexB/vulnerablecode#1341]
Hello everyone, 

The default improver job "vulnerabilities.improvers.default.DefaultImprover" uses over 70 GB of RAM and runs for more than 1 day. 
Is this behavior normal? You should try to allocate less memory. What are the requirements for VulnerableCode? 

Suggestion:
The improver should start with the new CVEs and not with those from Year 1999. To obtain the current CVEs more quickly. 

**Environment:** 
VulnerableCode Version: v32.0.0rc4

**VM:**
CPU: 8x Core Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
RAM: 128 GB

free -g 
               total        used        free      shared  buff/cache   available
Mem:             125          **70**          53           0           2          54
Swap:              0           0           0

**Database:** 
CPU: 4x Core
RAM: 32 GB

**CLI:** 
python3 ./manage.py improve vulnerabilities.improvers.default.DefaultImprover

Thanks

**Comment by pombredanne** [comment]
Thanks for the report!
See https://github.com/nexB/vulnerablecode/blob/main/CHANGELOG.rst#version-v3020 as we have made major refactoring since v32.0.0rc4

>  The improver should start with the new CVEs and not with those from Year 1999. To obtain the current CVEs more quickly.

I like this! Can you enter a separate issue to track it?

**Comment by turambarturin** [comment]
Okay, I will try the new version of VulnerableCode. 
I have already created an Improvment Ticket #1342. 

Thanks

**Comment by TG1999** [comment]
@turambarturin can we close this issue now ?

**Comment by turambarturin** [comment]
Yes, sure.
