### ISSUE TITLE
Bug in vulnerability details view 

### ISSUE THREAD

**Issue by TG1999** [nexB/vulnerablecode#1356]
![Screenshot from 2023-12-05 14-33-41](https://github.com/nexB/vulnerablecode/assets/34160672/86b6a7bc-8807-42f6-be6f-47448f63503a)

**Comment by johnmhoran** [comment]
@TG1999 Can you please describe the bug?

**Comment by TG1999** [comment]
The border on the first table in the page is missing.

**Comment by TG1999** [comment]
@johnmhoran if you will check main branch, it does not have a border

**Comment by TG1999** [comment]
> But I would like us to fix the dupe PURL issue and the search/lookup issue we've been discussing as well -- these are implicated in the number and characteristics of packages returned from a search in the UI/API and thus directly impact my planned consolidation in the vuln details view of the affected packages-fixed by packages tabs. Can we do that?

@johnmhoran that's in progress here https://github.com/nexB/vulnerablecode/tree/package-purl-model-updates

**Comment by TG1999** [comment]
> OK, noted, will add to my list of issues to tackle when I get to working on the vulnerability UI/API.

Alright, FYI this may be a deployment blocker.

**Comment by johnmhoran** [comment]
@TG1999 Hmm.  I just checked out `main` locally, without any current pull (in log last item is your Nov 27 `Prepare for release v33.6.3 (#1348)` commit), and the table has a border.  I'll do a git pull and see how it looks.

![image](https://github.com/nexB/vulnerablecode/assets/11096678/67e8f5f2-e98e-4555-addd-fbb796e9d100)

**Comment by johnmhoran** [comment]
In main, after a git pull, ran make run and ... there's a border.  Perhaps I missed a step, e.g., after doing git pull in main and before make run?  
![image](https://github.com/nexB/vulnerablecode/assets/11096678/1403a100-35e0-4348-8afa-730095d201ac)

**Comment by johnmhoran** [comment]
@TG1999 My prior screenshots were in Chrome.  But in Firefox, I can no longer see that table's border!?  
![image](https://github.com/nexB/vulnerablecode/assets/11096678/61edc44c-e6f1-4c3a-94d9-dbad4031728c)

**Comment by johnmhoran** [comment]
@TG1999 In Chrome the color of the top table's borders looks lighter than the border of the table below -- maybe Firefox displays that color differently?  In any event they should have the same colored border (tho not sure if that would change the display).

**Comment by johnmhoran** [comment]
otoh looking in Firefox at the current hosted VCIO does show the top table's borders, fwiw.

**Comment by johnmhoran** [comment]
For some reason Firefox and Chrome seem to be using different CSS.  These are both from my updated local main, Firefox then Chrome -- even the indentation differs.  
![image](https://github.com/nexB/vulnerablecode/assets/11096678/3e3beed8-f446-4e26-b95c-546fd7d064e1)
![image](https://github.com/nexB/vulnerablecode/assets/11096678/6f727279-763b-4582-84bc-30149604f700)

**Comment by johnmhoran** [comment]
@TG1999 I need to update my prior comments -- in Chrome, I'd neglected to hit ctrl-F5 to refresh the CSS, and when I do, in my local instance the top table has no borders and has the same indentation/horizontal alignment as Firefox.  This is the refreshed Chrome displaying the updated `main` locally:

![image](https://github.com/nexB/vulnerablecode/assets/11096678/0c978b3c-63d2-486f-884d-0720ba761f3a)

Both Chrome and Firefox when refreshed still display the borders for the public VCIO.  

The latest merge into `main` is my Package UI/API PR.  I don't recall doing any Vulnerability UI-related work in that PR but am guessing some change I made removed the borders and changed the indent/alignment.  Will dig into that now.

**Comment by johnmhoran** [comment]
Looks like my CSS change for the Package details table borders gave effect to a previously-overidden prior border=0 setting for that Vulnerability details table.  Creating a new branch to fix.

**Comment by johnmhoran** [comment]
Fixed with https://github.com/nexB/vulnerablecode/pull/1358 and merged in December 2023.  Closing.
