### ISSUE TITLE
Next/latest non-vulnerable version entries are missing from the public Package details page

### ISSUE THREAD

**Issue by johnmhoran** [nexB/vulnerablecode#1385]
I've just begun exploring the updated public VCIO inter alia to see what the recently-deduped PURL data looks like, and I see that in the Package details page, there are no longer entries for `Next non-vulnerable version` or `Latest non-vulnerable version`.  No idea why or what happened.  Did we decide to remove those?  I did recently see a PR to do some sort of "fix" on the Package details UI -- is that related?  (https://github.com/nexB/vulnerablecode/pull/1384)

In a search for, e.g., `pkg:composer/microweber/microweber@0.93`, compare the current public UI

![image](https://github.com/nexB/vulnerablecode/assets/11096678/7c1008ab-c0e1-4831-b5fd-0eb07a006907)

with my local version (using the `1079-create-suse-oval-importer` branch for the recently completed SUSE OVAL Importer PR -- my local DB does not yet reflect the revised DB structure and content, which likely explains why there are many empty cells in the `Fixed by` column on my local instance):

![image](https://github.com/nexB/vulnerablecode/assets/11096678/b45ceb1d-4ba8-4dc0-ac30-1f68a1b7b618)

**Comment by TG1999** [comment]
@johnmhoran please check https://public.vulnerablecode.io/packages/pkg:composer/microweber/microweber@0.93?search=pkg:composer/microweber/microweber@0.93 and let us know

**Comment by johnmhoran** [comment]
The next/latest non-vulnerable version entries are visible again; and the way we display the data when the Package has 0 affecting vulnerabilities looks great as well.  Thank you @TG1999 .  👍

**Comment by johnmhoran** [comment]
Looks like this issue was resolved shortly after I opened it back in January, and I'm belatedly closing it now.  Thank you @TG1999 .
