### ISSUE TITLE
500 being thrown by https://public.vulnerablecode.io/packages/pkg:alpine/py3-lxml@4.5.1-r1%3Farch=aarch64&distroversion=v3.12&reponame=community?search=lxml

### ISSUE THREAD

**Issue by TG1999** [nexB/vulnerablecode#1387]

**Comment by TG1999** [comment]
@DennisClark please check https://public.vulnerablecode.io/packages/pkg:alpine/py3-lxml@4.5.1-r1%3Farch=aarch64&distroversion=v3.12&reponame=community?search=lxml again on public instance and let us know

**Comment by DennisClark** [comment]
@TG1999    the problem is fixed in v34.0.0rc2  thanks !
