### ISSUE TITLE
Debian vulnerabilities are by default looked for 'jessie' release

### ISSUE THREAD

**Issue by sbs2001** [nexB/vulnerablecode#139]
https://github.com/nexB/vulnerablecode/blob/742625312ea393341cc5e1bb0e8c6f93d4706d59/vulnerabilities/scraper/debian.py#L30

Also their is no way  for the user to specify the release.

**Comment by pombredanne** [comment]
This would need to have https://github.com/nexB/vulnerablecode/issues/123 done first

**Comment by sbs2001** [comment]
Fixed via https://github.com/nexB/vulnerablecode/pull/152
