### ISSUE TITLE
Add URL to the vulnerability details view in the API serializers

### ISSUE THREAD

**Issue by tdruez** [nexB/vulnerablecode#1419]
For example, in the https://public.vulnerablecode.io/api/vulnerabilities/14104?format=json results, I'd like to have a field that includes the URL https://public.vulnerablecode.io/vulnerabilities/VCID-2v89-k9c8-aaah value.

This is required to provide a link to resources when displaying the API results, see https://github.com/nexB/dejacode/issues/4

The field name could be something along `resource_url` or `view_url`.

Note that this should be added to all the API serializers that have a details view in the main UI, like packages.

**Comment by barkhaaroraa** [comment]
could i work on this issue?

**Comment by pombredanne** [comment]
@barkhaaroraa I think that @TG1999 has it mostly solved

**Comment by TG1999** [comment]
closed by https://github.com/nexB/vulnerablecode/pull/1423
