### ISSUE TITLE
Change label from "Fixed by vulnerabilties" to "Fixes vulnerabilities"

### ISSUE THREAD

**Issue by TG1999** [nexB/vulnerablecode#1501]
![Screenshot from 2024-07-05 21-31-31](https://github.com/nexB/vulnerablecode/assets/34160672/f24e90ce-930b-4ae2-94b3-37bc7de203d0)

**Comment by johnmhoran** [comment]
@TG1999 There's no description -- please explain the thinking behind the change you suggest.  We've changed the names of these columns several times already in the past -- happy to change again if that what the group wants, but I haven't heard from others that that's what they want.

**Comment by johnmhoran** [comment]
Not sure if this is helpful, but one way to describe the relationship we're trying to name --  from the PURL's viewpoint, the PURL is "affected by" a vuln or "fixes" a vuln; and from the vuln perspective, the vuln "affects" the PURL or is "fixed by" the PURL.  🤔

**Comment by mjherzog** [comment]
I think that the current parallel "by" construction makes the most sense.

**Comment by johnmhoran** [comment]
@mjherzog @pombredanne When you have the chance, please share your views on the latest suggestion -- "Fixes vulnerabilities".

**Comment by pombredanne** [comment]
What I see most commonly is "fixed vulnerabilities" from a  package point of view, not "fixes vulnerabilities". Juts removing the "by" should be enough

**Comment by johnmhoran** [comment]
Thanks @pombredanne.  I'll make the change you suggest: "Fixed by vulnerabilties" ==> "Fixed vulnerabilities".

**Comment by pombredanne** [comment]
Closed and merged in the issue https://github.com/nexB/vulnerablecode/issues/1520 that tracks changes in the models, API and UI at once
