### ISSUE TITLE
Remove api calls to circl

### ISSUE THREAD

**Issue by sbs2001** [nexB/vulnerablecode#151]
This is a reminder to remove these api calls as well as it's functionality  which were probably used earlier for experments.
https://github.com/nexB/vulnerablecode/blob/848ee1285f8c6bdbc1245e59eb788b405cbe2088/vulnerabilities/api_data.py#L29 .

**Comment by aniket-chowdhury** [comment]
Hey, want to work on this. Why is there a need to remove these api calls?

**Comment by aniket-chowdhury** [comment]
It would break functionality as it is being called twice in [views.py](https://github.com/nexB/vulnerablecode/blob/848ee1285f8c6bdbc1245e59eb788b405cbe2088/vulnerabilities/views.py#L31).

**Comment by haikoschol** [comment]
@aniket-chowdhury This ticket is a bit short on context: We want to remove all URL endpoints that make use of this external API, not just the outgoing HTTP call itself. That includes the routes in [vulnerabilities/urls.py](https://github.com/nexB/vulnerablecode/blob/848ee1285f8c6bdbc1245e59eb788b405cbe2088/vulnerabilities/urls.py) and the related view functions.

**Comment by sbs2001** [comment]
My bad, anyways the issue is updated.

**Comment by sbs2001** [comment]
more context https://github.com/nexB/vulnerablecode/issues/9
