### ISSUE TITLE
NPM importer is down

### ISSUE THREAD

**Issue by sbs2001** [nexB/vulnerablecode#162]
```
>>> npm.scrape_vulnerabilities()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/vulnerablecode/vulnerabilities/scraper/npm.py", line 120, in scrape_vulnerabilities
    response = json.load(urlopen(cururl))
  File "/home/gitpod/.pyenv/versions/3.7.6/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/gitpod/.pyenv/versions/3.7.6/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/gitpod/.pyenv/versions/3.7.6/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/gitpod/.pyenv/versions/3.7.6/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/gitpod/.pyenv/versions/3.7.6/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/gitpod/.pyenv/versions/3.7.6/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable
```

**Comment by sbs2001** [comment]
Apparently, the importer is stuck on first page i.e it doesn't move on to next pages. It is stuck on 'https://registry.npmjs.org/-/npm/v1/security/advisories?page=0'.

**Comment by haikoschol** [comment]
> Apparently, the importer is stuck on first page i.e it doesn't move on to next pages. It is stuck on 'https://registry.npmjs.org/-/npm/v1/security/advisories?page=0'.

How did you come to this conclusion? In the traceback you posted the NPM registry was unavailable. Did you try again and then conclude that it was stuck on the first page?

The URL to the next page is still included in the JSON returned from the registry:
```
$ curl -s "https://registry.npmjs.org/-/npm/v1/security/advisories?page=0" | jq .urls.next
"/-/npm/v1/security/advisories?page=1"
```

And I just ran the NPM import successfully on my machine. Looks like this was just a temporary outage of the registry.

**Comment by sbs2001** [comment]
I was stuck in loop just requesting  "https://registry.npmjs.org/-/npm/v1/security/advisories?page=0", that  maybe crossing some threshold and giving 503 error . 

More specifically : https://github.com/nexB/vulnerablecode/blob/80a7b6e50c37dc599f28351f3e132e8bacbc551f/vulnerabilities/scraper/npm.py#L118

     https://github.com/nexB/vulnerablecode/blob/80a7b6e50c37dc599f28351f3e132e8bacbc551f/vulnerabilities/scraper/npm.py#L122

here the `nextpage ` variable was not updated

**Comment by sbs2001** [comment]
Here is a fresh test, that I just did. I have simply added a `print(cururl)`

```
>>> import npm
>>> npm.scrape_vulnerabilities()
https://registry.npmjs.org/-/npm/v1/security/advisories?page=0
https://registry.npmjs.org/-/npm/v1/security/advisories?page=0
https://registry.npmjs.org/-/npm/v1/security/advisories?page=0
https://registry.npmjs.org/-/npm/v1/security/advisories?page=0
https://registry.npmjs.org/-/npm/v1/security/advisories?page=0
............
```

**Comment by haikoschol** [comment]
You are right, it was stuck. In fact apparently it never worked. I just assumed it did when I started the command and it didn't throw any errors.
However, the fix is very simple: Just rename `next_page` to `nextpage`. Looks like I messed that up when "refactoring" and it was never caught.

**Comment by sbs2001** [comment]
That's what thought, but due to some 'abnormalities' in the advisories that won't be enough to have the importer up and running, I have elaborated this in the  comment at the PR
