### ISSUE TITLE
Debian importer is  treating lots of non-cves like cves

### ISSUE THREAD

**Issue by sbs2001** [nexB/vulnerablecode#165]
```
>>> z = pickle.load(open('debi.pickle','rb'))
>>> for i in z :
...     if not i['cve_id'].startswith('CVE') :
...             print(i['cve_id'])
... 
TEMP-0105562-0FE13B
TEMP-0582798-329FE7
TEMP-0000000-DEED53
TEMP-0000000-75B37A
TEMP-0000000-106DD8
TEMP-0774898-681A65
TEMP-0532740-DB1B64
TEMP-0000000-481246
TEMP-0579087-7F12A8
TEMP-0841257-B7CD60
........................
```
These are further dumped directly https://github.com/nexB/vulnerablecode/blob/c5c69a46f2476056158cfb87bdc304baabba5eba/vulnerabilities/data_dump.py#L38 . So basically we are having non-cve ids  in cve fields.

The `debi.pickle` was obtained by pickling https://github.com/nexB/vulnerablecode/blob/c5c69a46f2476056158cfb87bdc304baabba5eba/vulnerabilities/scraper/debian.py#L76

**Comment by haikoschol** [comment]
The bug is in `extract_vulnerabilities()` assuming that the object key in the JSON response always contains a CVE ID. Apparently Debian publishes advisories with temporary IDs when no CVE ID is available yet. The obvious next question then is how do those temporary IDs turn in to CVE IDs and how would we detect that and update our database accordingly?

**Comment by sbs2001** [comment]
https://deb.freexian.com/extended-lts/tracker/data/fake-names apparently these are automatically generated. 

> These names are not stable and can change when the database is updated, so they should not be used in external references. 

Should we just ignore these vulnerabilities for now ?

**Comment by haikoschol** [comment]
Either we ignore them or we don't store the temp ID and hope the summary won't change so we can find the entry again when it needs to be updated with a CVE ID.

**Comment by sbs2001** [comment]
I think ignoring would be better instead of later finding them and adding CVE ID, because if in case it doesn't get CVE ID we will end up with garbage data.

**Comment by sbs2001** [comment]
Closed in favour of https://github.com/nexB/vulnerablecode/issues/300
