### ISSUE TITLE
Use `requests.Session` in all `VersionAPI` classes

### ISSUE THREAD

**Issue by haikoschol** [nexB/vulnerablecode#187]
Several importers have a small helper class that allows fetching all versions of a given package and caching the response. Change the code that sends the request to use `requests.Session` instead of `urllib`. The main benefit is that this re-uses TCP connections for requests to the same host, so should provide a performance boost for this use case.

**Comment by sbs2001** [comment]
I don't think using `requests.Session`  would make any noticeable difference as most of the time is blocked  waiting for the response . I've mentioned this before, this would be best handled by some async solution ( aiohttp?), that would dramatically increase performance. I might be wrong but we could use async, as our ORM operations are decoupled from  fetching the data, don't know whether that would be a lot of work. 

FWIW using `requests.Session` won't hurt, but it won't make any difference which we care about.

**Comment by haikoschol** [comment]
I see. Intuitively I'd say reusing the connection is worthwhile but admittedly haven't given it much thought. I also haven't looked into possibilities to use async network I/O together with Django, but that definitely seems like it would be more work.
Anyway, if someone comes along looking for an easy ticket to get started, they can make this small change and do some profiling. If not, we just leave it as is.

**Comment by sbs2001** [comment]
VulnerableCode now uses async everwhere to API calls via https://github.com/nexB/vulnerablecode/pull/236, hence closing this
