### ISSUE TITLE
Collect Ubuntu vulnerability data

### ISSUE THREAD

**Issue by pombredanne** [nexB/vulnerablecode#19]
There are a couple ways to get Ubuntu vulnerabilities data from the main https://people.canonical.com/~ubuntu-security page:

1. An XML oval feed at https://people.canonical.com/~ubuntu-security/oval/
2. HTML pages that can be scraped at https://people.canonical.com/~ubuntu-security/cve/ ... for instances at https://people.canonical.com/~ubuntu-security/cve/main.html
3. possibly other sources such as 
  - a [bzr repo](https://code.launchpad.net/~ubuntu-security/ubuntu-cve-tracker/master) 
  - an [RSS/Atom](https://usn.ubuntu.com/usn/) feeds for higher level security notices for several vulns at once 

Some notes:

### About oval
The oval feed is likely a preferred option if it is comprehensive and contains data we need. This needs to be verified. For oval there is likely parsing code that could be reused in via4cve ... see [this](https://github.com/cve-search/VIA4CVE/blob/4b971689d286ce58e8678dee654191769a45ddc2/sources/OVAL.py)  or this for [redhat](https://github.com/cve-search/VIA4CVE/blob/4b971689d286ce58e8678dee654191769a45ddc2/sources/RedHatInfo.py) that may be using oval. 

### About the bzr repo

There may be also interesting stuff in the bzr repo: 

- there is a [README](http://bazaar.launchpad.net/~ubuntu-security/ubuntu-cve-tracker/master/view/head:/README) that looks maintained and up-to-date... and quite dense!
- for instance this looks like deb822 documents, one for each vulnerability: http://bazaar.launchpad.net/~ubuntu-security/ubuntu-cve-tracker/master/files/head:/active/
- the HTML pages in 2. seem to be created using scripts found there: http://bazaar.launchpad.net/~ubuntu-security/ubuntu-cve-tracker/master/files/head:/scripts/ and specifically here: http://bazaar.launchpad.net/~ubuntu-security/ubuntu-cve-tracker/master/view/head:/scripts/html-report ... therefore there may be an option to build on this rather than scraping the HTML.
- the scripts `./scripts/oval_lib.py` and `./scripts/generate-oval` are likely used to generate the oval XML too.

**Comment by kartiksibal** [comment]
In the OVAL data there isn't as much detail about packages, as much we'd like to establish a good package-vulnerability tie. There's a great deal of data, specifically about vulnerabilities, not so much about packages which is our key area.
