### ISSUE TITLE
Essential modifications required in Models.

### ISSUE THREAD

**Issue by kartiksibal** [nexB/vulnerablecode#22]
![27684353-f70208d0-5cc9-11e7-9f65-158b8c57f57a](https://user-images.githubusercontent.com/10362901/28500472-8bbfcef6-6fe6-11e7-8767-4a243837c726.png)

This is our present model.

**Some things to consider:**

1. CVSS should be in `Vulnerability Reference` and not in `Vulnerability`, since, CVSS scores are assigned to particular `CVE-IDs`
2. There should be some distinction in b/w a vulnerable package version and fixed version. Atm, we store just the fixed version.

**Comment by pombredanne** [comment]
Can you outline here or push some branch with new models?

**Comment by sbs2001** [comment]
Closing this stale ticket, but I guess this was fixed in https://github.com/nexB/vulnerablecode/pull/290
