### ISSUE TITLE
Add Mattermost security updates

### ISSUE THREAD

**Issue by pombredanne** [nexB/vulnerablecode#224]
See https://mattermost.com/security-updates/

**Comment by tushar912** [comment]
@pombredanne Can i work on this?

**Comment by Pushpit07** [comment]
Do you mean that the data here in this screenshot is to be scraped?

<img width="1306" alt="Screenshot 2021-03-19 at 09 23 52" src="https://user-images.githubusercontent.com/57194612/111729341-d846fb80-8894-11eb-9e53-7e0d7ab9b53b.png">

**Comment by prathamaror** [comment]
can i start working on this?

**Comment by armijnhemel** [comment]
It might be useful to subscribe to the security mailing list instead of scraping the webpage.

**Comment by TG1999** [comment]
dependent on https://github.com/nexB/univers/pull/97
