### ISSUE TITLE
Adopt calver

### ISSUE THREAD

**Issue by pombredanne** [nexB/vulnerablecode#250]
Because vulnerablecode provides both data and code and that each are not dissociableand that data needs to be kept current to ensure up to date vulnerability data I suggest we switch to use a calver version scheme http://calver.org/ as in YY.minor.micro where YY would be the year on two digits, minor a month. Micro would be used only if needed between month versions. If there is agreement, I would like to implement this change for the upcoming release.

**Comment by pombredanne** [comment]
@sbs2001 @haikoschol ping

**Comment by sbs2001** [comment]
VulnerableCode now uses cal ver https://github.com/nexB/vulnerablecode/releases/tag/v20.10
