### ISSUE TITLE
Deploy on public server

### ISSUE THREAD

**Issue by pombredanne** [nexB/vulnerablecode#253]
- [x] Decide on a DNS domain name and acquire name
- [x] Provision server (Philippe), possibly with GCP credits at least for the initial DB creation
- [x] create deploy and backup scripts
- [x] deploy proper

**Comment by pombredanne** [comment]
@edoardolanzini ping, FYI

**Comment by sbs2001** [comment]
The temp domain for now would be  https://vulnerablecode.aboutcode.org

**Comment by pombredanne** [comment]
@sbs2001 I registered for now vulnerabilitydb.org which is simple and generic

**Comment by pombredanne** [comment]
and I provisioned a dedicated server

**Comment by pombredanne** [comment]
This has been deployed (with a simple PW until final release 30.0.0 is tagged) at https://public.vulnerablecode.io/ :tada:

**Comment by pombredanne** [comment]
@sschuberth there is a new release coming up and we added API doc and self registration for an API key
This is may be released this week.

**Comment by sschuberth** [comment]
> self registration for an API key

Would you be OK with exposing an API key for ORT in a public example ORT pipeline that leverages VulnerableCode, @pombredanne?

**Comment by pombredanne** [comment]
And this is now live at https://public.vulnerablecode.io/

**Comment by pombredanne** [comment]
> Would you be OK with exposing an API key for ORT in a public example ORT pipeline that leverages VulnerableCode, 

Your call. An API key is like a password... and API calls should be throttled. Getting an API key should be easy enough

**Comment by sschuberth** [comment]
> And this is now live at https://public.vulnerablecode.io/

This is what I get when requesting an API key:

![image](https://user-images.githubusercontent.com/349154/200763351-c7422da5-0c7b-4a4d-b7d1-4ea8315213c9.png)

**Comment by pombredanne** [comment]
@sschuberth This is now fixed! Sorry for the noise!

**Comment by sschuberth** [comment]
I've got my API key now, but unfortunately I'm getting "Authentication credentials were not provided." for any API call that I tried so far despite an "Authorization" header with my token being present.

**Comment by sschuberth** [comment]
> despite an "Authorization" header with my token being present.

Ah, the value of that header field needs to [start with the literal word "Token" before the token's value](https://github.com/nexB/vulnerablecode/blob/c9f70a0b1b0997d66042498e62ebbf28b8458199/docs/source/api.rst#access-the-api-using-curl)!

Could you fix the cURL code generated at https://public.vulnerablecode.io/api/docs/ to include that?

**Comment by pombredanne** [comment]
Let me reopen this issue
In the OpenAPI at https://public.vulnerablecode.io/api/docs/ if I click on Authorize, the popup states:

```
Available authorizations

tokenAuth (apiKey)

Token-based authentication with required prefix "Token"

Name: Authorization

In: header
Value:
```

Where do you think we could make this more obvious?

**Comment by TG1999** [comment]
Thanks @sschuberth , closing this!
