### ISSUE TITLE
Relationships between a Package and Vulnerability are not created

### ISSUE THREAD

**Issue by tdruez** [nexB/vulnerablecode#27]
During the data dump, `debian_dump` and `ubuntu_dump` https://github.com/nexB/vulnerablecode/blob/develop/app/vulncode_app/data_dump.py#L29 and https://github.com/nexB/vulnerablecode/blob/develop/app/vulncode_app/data_dump.py#L47

The Vulnerability and Package objects are created but not the relationship (`ImpactedPackage`, `ResolvedPackage`) between the 2.

This make the data un-usable.

**Comment by kartiksibal** [comment]
Yes, I had looked into that and updated. This will reflect in the next commit.
