### ISSUE TITLE
Add Sonatype OSS Index as a data source

### ISSUE THREAD

**Issue by sschuberth** [nexB/vulnerablecode#276]
Already mentioned at https://github.com/nexB/vulnerablecode/issues/106, I'm particularly interested in getting the [Sonatype OSS Index](https://ossindex.sonatype.org/) as a data source, in the context of [using VulnerableCode in ORT](https://github.com/oss-review-toolkit/ort/issues/3287). I'm splitting this out as a separate issue to be able to track this individually.

https://github.com/dotanuki-labs/gradle-bodyguard already seems to have some Python code to query the OSS Index, which might be worth a look.

**Comment by sbs2001** [comment]
@sschuberth  thanks for considering to use VulnerableCode at ORT. 

I had looked at Sonatype OSS Index a long time ago. The problem with Sonatype OSS Index as a data source, is that it provides no way to obtain `package->vulnerablity` mappings in case we don't have  have a  list of `packages` already(before running the import).  And vulnerablecode atm is just a DB, not a scanner. 

For eg check the API at https://ossindex.sonatype.org/rest , it needs the purl `coordinates` . 

So we essentially want  all the purls for which oss index has data for. One way of getting there would be to run all the existing importers and then iterate  and query OSS index's API for all collected purls from other data sources.

Is there any better way to do this ? 

@pombredanne ^

**Comment by sschuberth** [comment]
Can't you simply do it on demand? I'm not sure how VulnerableCode works internally, but I would have expected it to be able to work as a "dispatcher" that, given some coordinates in PURL or another format, is able to query all known data sources for those coordinates.

But what you're saying sounds more as if VulnerableCode was some kind of mirror, which imports all data from all known sources (incrementally) at some intervals. Which means that your data source needs to be able to provide access to all data at once / in bulk, and not only to query with specific coordinates. Is it that what you mean?

**Comment by sbs2001** [comment]
>VulnerableCode was some kind of mirror, which imports all data from all known sources (incrementally) at some intervals

Exactly ! Atleast for now you can call it that.  It collects data from these sources and converts it into the `purl->vulnerability` format. Once data is imported you can use just vulnerablecode as a single dispatcher which would be equivalent to querying each data source individually.

**Comment by sschuberth** [comment]
I see.

>  iterate and query OSS index's API for all collected purls from other data sources.

Unfortunately, I believe this would not work well, as OSS Index seems to complement the existing data sources and probably contains information about many components / languages that are not covered in the other data sources.

**Comment by sschuberth** [comment]
Thanks to @pombredanne who separately pointed out to some issues with the OSS Index's [terms of service](https://ossindex.sonatype.org/tos) what would prevent us from integration into VulnerableCode, which I've also summarized [here](https://github.com/oss-review-toolkit/ort/issues/718#issuecomment-731150111).

**Comment by pombredanne** [comment]
The comments from https://github.com/oss-review-toolkit/ort/issues/718#issuecomment-731150111 are:

> There might be some issues with their [terms of use](https://ossindex.sonatype.org/tos) that could prevent us from integration:
> 
> > you may access and use the Materials solely for your internal use.
> 
> > you may not [...] Analyze or use the Offering in any way that is or may be competitive with Company.
> 
> > you may not [...] incorporate any portion of the Offering into any product or service [...]
> 
> > you may not [...] Systematically download and store any or all of the Offering’s content.
> 
> > you may not [use a] retrieval application or other manual or automatic device to retrieve, index, “scrape,” “data mine” or otherwise gather the Offering’s content [...]

Basically OSSIndex ToS and license is 100% proprietary and there is nothing that can be done with this at all.
