### ISSUE TITLE
Collect Elixir security advisories

### ISSUE THREAD

**Issue by sbs2001** [nexB/vulnerablecode#287]
Import data from https://github.com/dependabot/elixir-security-advisories

**Comment by tushar912** [comment]
@sbs2001 Can I work on this?

**Comment by sbs2001** [comment]
@tushar912  sure . Let me know if you need any help :)

**Comment by sbs2001** [comment]
You would need to obtain all the versions of a specific package to resolve the version ranges from advisories. 

The API at https://hex.pm/api/packages/{package_name}  provides this info 

eg 
https://hex.pm/api/packages/phoenix (look into `releases`)

**Comment by tushar912** [comment]
@sbs2001 Thanks

**Comment by tushar912** [comment]
@sbs2001 I had a doubt the packages contain <code>patched_versions</code> and <code>unaffected_versions</code> do they both need to be included in <code>safe_packages</code>

**Comment by sbs2001** [comment]
Could you point me to an example ? 

For now they both belong to `safe_packages` .

**Comment by tushar912** [comment]
@sbs2001 Sorry I was referring to this
```json
---
id: 46aad699-50a3-48d8-a7ac-f248ab96b374
package: ecto
disclosure_date: 2017-08-27
cve:
link: https://groups.google.com/forum/#!topic/elixir-ecto/0m4NPfg_MMU
title: |
  Missing `is_nil` requirement
description: |
  Ecto will not raise on queries with non-explicit nil comparisons (ie if they aren't checked with `is_nil`).
patched_versions:
  - "> 2.2.0"
unaffected_versions:
  - "< 2.2.0"
```
I think both patched and unaffected refer to <code>safe_packages</code>. Please correct me if I am wrong

**Comment by sbs2001** [comment]
>I think both patched and unaffected refer to safe_packages

Yes you are correct indeed .

**Comment by tushar912** [comment]
@sbs2001 What should i write in <code>type</code> here <code>safe_purls ={ PackageURL(name=pkg_name,
                type=pkg_type,
                version=version)
                for version in safe_pkg_versions}</code>

**Comment by sbs2001** [comment]
Ah, I should I've told you this before,  from https://github.com/package-url/purl-spec I see the `type` would be `hex` .
