### ISSUE TITLE
django based app, which combines DRF api & cve-search instance.

### ISSUE THREAD

**Issue by kartiksibal** [nexB/vulnerablecode#3]
To Do:

1. Initialise a django based app. ✅ 
2. Using the cve-search api code return CVE-IDS. ✅ 
3. Output the data in JSON format. ❎ 

__EDIT:__

Additions in second point:

1. CVSS Score ❎ 
2. Summary ❎ 
3. URL ❎

**Comment by kartiksibal** [comment]
@tdruez @pombredanne Please guide any changes that might be necessary in the todo, 

thanks

**Comment by pombredanne** [comment]
sure!

**Comment by pombredanne** [comment]
Merged. Closing. This is a basic API that does not use DFR for now,
