### ISSUE TITLE
Collect Istio

### ISSUE THREAD

**Issue by sbs2001** [nexB/vulnerablecode#302]
See https://istio.io/latest/news/security/

**Comment by tushar912** [comment]
@sbs2001 can I work on this

**Comment by sbs2001** [comment]
@tushar912  that would be great :)

**Comment by sbs2001** [comment]
@tushar912  any issues ? 

I found the same thing at https://github.com/istio/istio.io/tree/master/content/en/news/security , which we should parse instead of the link I gave earlier. Since repo contains the required data in machine readable format.

**Comment by tushar912** [comment]
@sbs2001 Sorry I got busy with some other work so I could not make much progress. I will resume work on it. Thanks for the repo link.

**Comment by tushar912** [comment]
I think https://github.com/istio/istio.io/tree/master/content/en/news/releases can be used for finding all releases.

**Comment by sbs2001** [comment]
@tushar912  IMHO using https://github.com/nexB/vulnerablecode/blob/3b903ae24f812a6ad32f4422ae06385330c2367f/vulnerabilities/package_managers.py#L333 to query the releases of https://github.com/istio/istio would be simpler

**Comment by tushar912** [comment]
Oh forgot about it . Agree, that's better.

**Comment by tushar912** [comment]
@sbs2001 for resolving ranges in this (like 1.1 to 1.6) I don't think <code>dephell_specifier</code> can be used directly .So I was thinking of converting the range to something like <code>>=1.1 &&<=1.6</code> and then using <code>dephell_specifier</code> on it. Is this approach correct or should I try something else.

**Comment by sbs2001** [comment]
@tushar912  converting to  `>=1.1 &&<=1.6` is absolutely correct !

**Comment by tushar912** [comment]
@sbs2001 what should be the package type here

**Comment by sbs2001** [comment]
I think it should be either  `helm`  or `generic`. @pombredanne  ^ what do you think ?

**Comment by pombredanne** [comment]
> I think it should be either `helm` or `generic`. @pombredanne ^ what do you think ?

I could not not find an official helm chart for it and we can be better than generic. 
Instead what about using these two types since the only thing we know for sure is this is a GitHub and a Go package:
- `pkg:github/istio/istio@1.5.8` based on https://github.com/istio/istio
- `pkg:golang/istio.io/istio@1.8.0` based on https://pkg.go.dev/istio.io/istio

**Comment by tushar912** [comment]
@pombredanne which one should I use golang or github

**Comment by tushar912** [comment]
@sbs2001 @pombredanne I have made a PR( https://github.com/nexB/vulnerablecode/pull/336) for this. Added WIP just because I need to confirm the package type. Then I would add it to <code>SOURCES.rst</code>.
