### ISSUE TITLE
Store and archive ALL the data we fetch forever

### ISSUE THREAD

**Issue by pombredanne** [nexB/vulnerablecode#332]
This cache of the source data we use is an important piece of proper traceability.

**Comment by sbs2001** [comment]
I'm guessing we are to store this in filesystem

In that case I can think of having a structure like  `data_archive/<importer_name>/<TIMESTAMP>/Data`

**Comment by pombredanne** [comment]
Based on the latest design discussion where we would store advisories, this becomes moot: advisories are essentially the data we fetch (and practically the normalized subset of data we care for).
Therefore I am closing this as invalid now.
