### ISSUE TITLE
Package.version field needs proper definition

### ISSUE THREAD

**Issue by lohani2280** [nexB/vulnerablecode#34]
Currently, if I look at the JSON data from debian security tracker I find that it does not say which version is vulnerable but it says which is resolved/fixed. However,  if I look at the JSON data from arch linux security tracker I find that it contains both fixed version as well as vulnerable version. This creates ambiguity while dumping the data to the `Package.version` field. While in the case of debian we simply dump `fixed_version` value from the JSON data to `Package.version` field, which value should be dumped in `Package.version` field for arch linux, i.e, `affected_version` or `fixed_version` value?

arch linux security tracker data - https://security.archlinux.org/json
debian security tracker data - https://security-tracker.debian.org/tracker/data/json

**Comment by pombredanne** [comment]
You need to create as many packages as needed. Then update the relationships ImpactedPackage and ResolvedPackage between these packages and your vulnerability.

![VulnerableCode prototype models](https://user-images.githubusercontent.com/675997/54075877-b3325200-42a4-11e9-8b70-ef4a88a17b39.png)

**Comment by lohani2280** [comment]
@pombredanne Closing this as this is clear to me now.
