### ISSUE TITLE
Deal with  duplicate reference urls

### ISSUE THREAD

**Issue by sbs2001** [nexB/vulnerablecode#343]
![image](https://user-images.githubusercontent.com/28975399/107518768-66b0c900-6bd5-11eb-8ca3-df640266a824.png)

**Comment by sbs2001** [comment]
Explore storing canonical form of urls

**Comment by savish28** [comment]
Hey @sbs2001 regarding this issue I am thinking of overriding the save method of `VulnerabilityReference` model and overriding the instance URL with `str(urlpy.parse(instance_url).canonical())`.
Secondly, Do we want something to be done regarding http/https?

**Comment by sbs2001** [comment]
@savish28 thanks for looking into this,  your approach would indeed make things better. 

As for dealing with `http vs https`  we could either 

1. Have a script which removes the duplicates ?
or 
2.We could also override the save method to check for the same canonical url except with `https`/`http` and do things accordingly. 
If provided url is http but we already have the url with https we ignore the `http` url. 
If provided url is https but we already have the url with `http` we replace the `http` url with `https` one 

This approach would increase db hits tho

But in any case `str(urlpy.parse(instance_url).canonical())` would do only good.

**Comment by vignesh-cloud-prog** [comment]
Can i take up this

**Comment by sbs2001** [comment]
@savish28  are you working on this ?  

@vignesh-cloud-prog  this is a non trivial issue btw (not a good first )

**Comment by savish28** [comment]
@sbs2001 Yes, I would open a PR in some time.

**Comment by TG1999** [comment]
With the latest models the references can not be duplicated, closing this now.
