### ISSUE TITLE
FIx UI problems

### ISSUE THREAD

**Issue by sbs2001** [nexB/vulnerablecode#344]
Changes:-
- [x] 1. Make Packages -> Package . The columns should have singular name. 
- [x] 2. Eliminate whitespace from search result view.
- [x] 3. Don't forget what user searched for. 
- [x] 4. Correct sequencing in package search view. expectec -> Vulnerabilities| Patched Vulnerabilities
- [x] 5.  Unrelated to UI : Forget fixes, remember vulnerable packages only, while keeping track of first fix. 
- [x] 6. Have setting, to enable/disable curation. Set it to disabled by default. 
- [ ] #535
- [x] 8. Rename Package Details -> Packageurl

**Comment by sbs2001** [comment]
In the vulnerability view, for displaying vulnerable packages we need to avoid using discrete versions. Instead a expandable version range would be better, that will increase information density.

Here's a repaste from gitter chat on how to create version ranges from discrete version ranges

>For eg. Given a list of versions like [1.1.2, 1.1.3, 1.2.3, 1.2.4, 2.5.6]
We can convert it into version ranges having a lowest common denominator of either the MAJOR, MINOR . In this case let it be the MINOR part.
Then we split the version list into smaller lists, each of the list having same lowest common denominator and parts greater than it.
[1.1.2, 1.1.3, 1.2.3, 1.2.4, 2.5.6] -> [1.1.2, 1.1.3,], [1.2.3, 1.2.4], [2.5.6]
Now each of this smaller list can be coverted into version ranges of the format
<=max(version_list) , >=min(version_list)
In this case that will be <=1.1.3, >=1.1.2 etc

**Comment by pombredanne** [comment]
See #535 for a follow up. I am closing this for now otherwise.
