### ISSUE TITLE
Proper db migration process

### ISSUE THREAD

**Issue by uboznikov** [nexB/vulnerablecode#356]
After pulling latest and running the data import, encountered several missing db artifacts.

```
File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "vulnerabilities_vulnerabilityseverity" does not exist
LINE 1: ...lities_vulnerabilityseverity"."reference_id" FROM "vulnerabi...
                                                             ^
```

On start the db initialization is run only if the db does not exist.

`PostgreSQL Database directory appears to contain a database; Skipping initialization`

But should also account for updates on an existing db, similar to [Liquibase](https://www.liquibase.org/) or [Flyway](https://flywaydb.org/) (Java).

**Comment by sbs2001** [comment]
Could you try deleting the images and pulling again ? The problem is caused because the migrations have not been ran since a schema change

**Comment by uboznikov** [comment]
Ok that solves it.

Would it be possible if this can be done without deleting then re-creating the images?

**Comment by sbs2001** [comment]
> Would it be possible if this can be done without deleting then re-creating the images?

yes
you could do the following in the project dir 
```
sudo docker-compose up 
sudo docker-compose exec web bash
python manage.py makemigrations vulnerabilities
python manage.py migrate
```

**Comment by sbs2001** [comment]
> Would it be possible if this can be done without deleting then re-creating the images?

yes
you could do the following in the project dir 
```
sudo docker-compose up 
sudo docker-compose exec web bash
python manage.py makemigrations vulnerabilities
python manage.py migrate
```

**Comment by chess-equality** [comment]
Thanks.

But previously I also deleted then re-created images, could this be avoided at all?

https://github.com/nexB/vulnerablecode/issues/312

**Comment by sbs2001** [comment]
@chess-equality  yes, these both issues are caused  because the docker images and the code are out of sync.

When you pull latest, your code is latest. But the deps and schema remain same as that of intial image creation.

**Comment by DjDeepDive** [comment]
I would also suggest that proper migrations be included in the repo, if possible.  I realize this project is a free gift to the open source community, but it makes it difficult to keep up to date with your code having to re-scrape everything without a migration process (which is fairly easily created with Django).

**Comment by pombredanne** [comment]
@DjDeepDive 
1. thank you for the kind words!

2. yes, we need stable migrations alright! I guess the schema is still evolving fast but that's not a reason. Django has superb migration support.

@sbs2001 ping me on Gitter when you come online tomorrow so we can sync, I think you made the migration in your latest PR an initial migration?

**Comment by pombredanne** [comment]
@DjDeepDive with that said, if you can chip in to help too that would be mucho welcomed!

**Comment by DjDeepDive** [comment]
> @DjDeepDive with that said, if you can chip in to help too that would be mucho welcomed!

Gladly.  What needs done?

**Comment by sbs2001** [comment]
Migrations are not included (mainly because there would be tons of them and schema is evolving), hence causing this problem.  As a short term fix on these, a fake migration via 

```
python manage.py migrate --fake vulnerabilities zero
python manage.py migrate 
```
would do the trick. But ofcourse this is a hack. 

A proper solution would be to include all migrations in the repo

**Comment by pombredanne** [comment]
@sbs2001 IMHO we should start including them, even with fast schema updates, they should work well enough. @tdruez what's your advice there?

**Comment by tdruez** [comment]
> @sbs2001 Migrations are not included (mainly because there would be tons of them and schema is evolving)

I don't think it's a valid argument to not include migrations along code changes. Django provides ways to squash migrations when needed: https://docs.djangoproject.com/en/3.1/topics/migrations/#migration-squashing

As a side note, make sure to consolidate all the migrations of a branch into one file before merging a PR.

**Comment by pombredanne** [comment]
@tdruez Thanks for the insights!

**Comment by sbs2001** [comment]
@tdruez  thanks for the link. We will start with real "squashed migrations" hence forth rather than creating one fresh ;) 

Closing this I will take better care of migrations next time ;)
