### ISSUE TITLE
Add retire.js repo data

### ISSUE THREAD

**Issue by pombredanne** [nexB/vulnerablecode#37]
https://github.com/RetireJS/retire.js/tree/master/repository

**Comment by sbs2001** [comment]
Upon some superficial comparison of https://github.com/RetireJS/retire.js/blob/master/repository/npmrepository.json  and the data collected by npm importer, I can say we can safely avoid collecting npm advisories from this repo (it is also not updated). 

https://github.com/RetireJS/retire.js/blob/master/repository/jsrepository.json is what should be collected to close this issue, these are bower packages and the data seems unique.

**Comment by haikoschol** [comment]
@sbs2001 Thanks for looking into this!

**Comment by sbs2001** [comment]
After researching, this data : I've realized 

-  The packages mentioned in this data are all covered by our npm importer , this includes the ones from https://github.com/RetireJS/retire.js/blob/master/repository/jsrepository.json 

- The only value of importing these, is we will get their `bowernames`, bower is anyways dying. 

- The pain point of bower is that there is no easy way to obtain 'all versions' of a particular package, 
unless we install bower which comes with the overhead of  js ecosystem . Or we could use github api to fetch versions of packages(which is what `bower info pkg_name` does in background). 

My opinion is to close this issue, FWIW it will be lot of work to write importer for this.   
Here's some data analyis https://colab.research.google.com/drive/1IROxFgMK1qsnAvTaPLcldnbS5mVbTpZd

As you can see out of 34 packages 25 are covered by our  npm importer rest are some jquery components.
