### ISSUE TITLE
Use a more specific url for cvss qualitative severity system.

### ISSUE THREAD

**Issue by sbs2001** [nexB/vulnerablecode#372]
The url at is not specific.
https://github.com/nexB/vulnerablecode/blob/8cfb2bd5760d27259f425884926fec66a28798c2/vulnerabilities/severity_systems.py#L81 

Use a more specific url `https://www.first.org/cvss/specification-document#Qualitative-Severity-Rating-Scale` instead

**Comment by tushar912** [comment]
Taking it up.
