### ISSUE TITLE
Display severities in the vulnerability view 

### ISSUE THREAD

**Issue by sbs2001** [nexB/vulnerablecode#380]
In the view at http://127.0.0.1:8000/vulnerabilities/<vulnerability_id> we need to display the severity obtained from various data sources.

The severity must be nested inside the reference to show the connection.

**Comment by Pushpit07** [comment]
Opened a PR to add this feature

**Comment by Pushpit07** [comment]
Which field do you mean by severity in the VulnerabilitySeverity model?

```
class VulnerabilitySeverity(models.Model):

    scoring_system_choices = (
        (system.identifier, system.name) for system in scoring_systems.values()
    )  # nopep8
    vulnerability = models.ForeignKey(Vulnerability, on_delete=models.CASCADE)
    value = models.CharField(max_length=50, help_text="Example: 9.0, Important, High")
    scoring_system = models.CharField(
        max_length=50,
        choices=scoring_system_choices,
        help_text="identifier for the scoring system used. Available choices are: {} ".format(
            ", ".join(
                [
                    f"{ss.identifier} is vulnerability_id for {ss.name} system"
                    for ss in scoring_systems.values()
                ]
            )
        ),
    )
    reference = models.ForeignKey(VulnerabilityReference, on_delete=models.CASCADE)

    class Meta:
        unique_together = ("vulnerability", "reference", "scoring_system")
```

**Comment by Pushpit07** [comment]
Is it the scoring_system?

**Comment by sbs2001** [comment]
We need both, the scoring_system and value

**Comment by AmitGupta7580** [comment]
I have added the severity and scoring sytem field in vulnerability.html templete. Can I create a new PR.

![ui](https://user-images.githubusercontent.com/57043342/112274535-9bb83d00-8ca4-11eb-9995-098744581358.png)

**Comment by sbs2001** [comment]
@AmitGupta7580  @Pushpit07  is already working on this at https://github.com/nexB/vulnerablecode/pull/390 . We need some help with design there, see the comments there, any help would be appreciated :)

**Comment by vignesh-cloud-prog** [comment]
What is going on inthis issue
