### ISSUE TITLE
Fix KeyError in redhat importer 

### ISSUE THREAD

**Issue by sbs2001** [nexB/vulnerablecode#384]
The redhat importer is failing.

From the logs at https://pipelines.actions.githubusercontent.com/Ep9prel8NYELDl3abhBbfgiORCbX0JuViN8i8esKzVS8DdQt5i/_apis/pipelines/1/runs/130/signedlogcontent/3?urlExpires=2021-03-18T04%3A34%3A23.9071130Z&urlSigningMethod=HMACV1&urlSignature=sJLXLRjUZZiPl5J24k1eE1Ljte7e79N3jahByMOwWS8%3D

The issue is at
https://github.com/nexB/vulnerablecode/blob/8094f6e5fcea1023d50c29ae1ae01e291321974f/vulnerabilities/importers/redhat.py#L94

Investigate the erroneous response, and add some safety measure there

**Comment by savish28** [comment]
@sbs2001 Can I work on this?

**Comment by sbs2001** [comment]
@savish28  yes !
