### ISSUE TITLE
Fix docs URL in README.md

### ISSUE THREAD

**Issue by anshsrtv** [nexB/vulnerablecode#386]
The Readme states the following:

> For full documentation about API endpoints use this URL:
> ```
> http://127.0.0.1:8000/api/docs
> ```

There isn't any such page found. It should be replaced by 
```
http://127.0.0.1:8000/api/schema/swagger-ui/
```

**Comment by sbs2001** [comment]
That is fixed via https://github.com/nexB/vulnerablecode/pull/379
