### ISSUE TITLE
Add pylint.

### ISSUE THREAD

**Issue by singh1114** [nexB/vulnerablecode#39]
Add pylint to CI, to check basic things in the code.

**Comment by pombredanne** [comment]
Actually using pycodestyle may be moe aligned with other tests done. See https://github.com/nexB/aboutcode-toolkit/blob/dde73cbe462734bd4098508aa27234658781647f/tests/test_validate.py#L34

**Comment by singh1114** [comment]
@pombredanne Agreed.

**Comment by singh1114** [comment]
@pombredanne I think it's already there in the CI.
