### ISSUE TITLE
"Got an unexpected keyword argument 'cve_id'".

### ISSUE THREAD

**Issue by uboznikov** [nexB/vulnerablecode#396]
I ran into this error when importing `msr2019`.

![image](https://user-images.githubusercontent.com/16329085/111967118-9e932080-8b32-11eb-8f3e-8335429693f5.png)

**Comment by sbs2001** [comment]
@uboznikov  https://github.com/nexB/vulnerablecode/pull/378 fixes that error. Can't merge it since we have some problems in repo permissions. Will do once that is resolved.

**Comment by uboznikov** [comment]
@sbs2001 Thanks.

Also, this column `cve_id` seems to have been removed; has it been completely removed or moved to another table?

**Comment by sbs2001** [comment]
@uboznikov  that's renamed to  `vulnerability_id`

**Comment by sbs2001** [comment]
Fixed via https://github.com/nexB/vulnerablecode/pull/378
