### ISSUE TITLE
Replace objects.create with objects.update_or_create.

### ISSUE THREAD

**Issue by singh1114** [nexB/vulnerablecode#40]
Replace objects.create with objects.update_or_create along with new tests regarding this.

**Comment by pombredanne** [comment]
When you craft a ticket please make sure this is a statement of problem rather than a small solution like here.

The problem to have a ticket for is to support re-fetching vulnerability data from each source and handle properly the act that some data is the same and has not changed and some data has been updated.

**Comment by singh1114** [comment]
@pombredanne Will keep that in mind.

**Comment by haikoschol** [comment]
@singh1114 As far as I understand, #40 is about the following scenario (I trust @pombredanne to correct me if I'm wrong):

- MadeupLinux issues a security advisory about package foo 1.2.3, with the identifier `MUL-42`.
- We ingest this advisory.
- A mistake in the advisory is found, or it was missing crucial infomation, so some part of the advisory is revised. Maybe a notification is sent to the MadeupLinux Security Announce mailing list.
- We want to find out about this and update our copy of it.

My questions about this scenario are:

1. Does this actually happen and if so, how common is it?
2. If yes, we should be able to find out how (if at all) tools similar to vulnerablecode deal with it.
3. Is there some way to detect it when processing individual vulnerability sources (e.g. MadeupLinux Security Advisories). This could be in the form of timestamps.

**Comment by singh1114** [comment]
@haikoschol It would be awesome if we are able to get the timestamp data for a given package vulnerability. But I think we are not getting it currently.

**Comment by haikoschol** [comment]
@singh1114 Right, we are not. I don't know which, if any, of the vulnerability sources have such timestamps in their data model. We should find out and if they do, make use of them.

**Comment by sbs2001** [comment]
Closing this stale ticket but I guess this was fixed via https://github.com/nexB/vulnerablecode/pull/152 .
