### ISSUE TITLE
Navigation is not responsive

### ISSUE THREAD

**Issue by vignesh-cloud-prog** [nexB/vulnerablecode#424]
In mobile  and tablet view navigation is not available

**Comment by sbs2001** [comment]
This project is not aimed towards mobile users.

**Comment by pombredanne** [comment]
@sbs2001 re:

> This project is not aimed towards mobile users.

sure, but would it hurt to have minimal responsive support?

**Comment by vignesh-cloud-prog** [comment]
Not talking about animation. But about navigation
