### ISSUE TITLE
Add support for new GitLab community advisories

### ISSUE THREAD

**Issue by pombredanne** [nexB/vulnerablecode#438]
See https://gitlab.com/gitlab-org/advisories-community/
This is MIT-licensed per https://gitlab.com/gitlab-org/advisories-community/-/blob/main/LICENSE

This is time-delayed (read: outdated) : 
> This is an MIT-licensed, time-delayed clone of the GitLab Advisory Database that contains all advisories from the GitLab Advisory Database that are older than 180 days.
> For more information about the data format and for the contribution guidelines,
> please refer to the README.md of the GitLab Advisory Database.

**Comment by pombredanne** [comment]
Reported by @tsteenbe

**Comment by julianthome** [comment]
@pombredanne we recently reduced the time delay with which https://gitlab.com/gitlab-org/security-products/gemnasium-db advisories are populated to https://gitlab.com/gitlab-org/advisories-community/ from 180 down to 30 days.

**Comment by pombredanne** [comment]
@julianthome re

> we recently reduced the time delay


Thank you ++ !

**Comment by sschuberth** [comment]
Should this be added to https://github.com/nexB/vulnerablecode/blob/main/SOURCES.rst as well?
