### ISSUE TITLE
Use saneyaml instead of yaml

### ISSUE THREAD

**Issue by Hritik14** [nexB/vulnerablecode#440]
[saneyaml](https://github.com/nexB/saneyaml) is maintained by us (nexB) and it makes sense to update all the importers to use it instead of `yaml`.
Files currently requiring the fix.

- [x] - importers/suse_backports.py
- [x] - importers/elixir_security.py
- [x] - importers/istio.py
- [x] - importers/mozilla.py
- [x] - importers/alpine_linux.py
- [x] - tests/test_alpine.py
- [ ] - ~tests/test_suse_backports.py~
- [x] - helpers.py

**Comment by sbs2001** [comment]
@pombredanne  is there any advantage of using saneyaml over standard yaml . AFAIK there is `yaml.safe_load` , we really don't do nything else with it here.

**Comment by sbs2001** [comment]
After discussion with @pombredanne  I'm convinced that `yaml` is insane, and there is value in using  `saneyaml` .

**Comment by Hritik14** [comment]
@sbs2001 imho, if you could post that conversation here, it would be very helpful for future contributors.

**Comment by Hritik14** [comment]
Rationale:
```py
>>> yaml.load("phil: yes")
{'phil': True}
```
