### ISSUE TITLE
Improvement in Package bulk_search API

### ISSUE THREAD

**Issue by AmitGupta7580** [nexB/vulnerablecode#446]
- [ ] #543
- [ ] API documentation

Due to restricted change in schema of bulk_search API. The implementation of bulk_search API needs to be change.

Some Alternatives :

- Nest the result inside some variable and return `JSON` object. https://github.com/nexB/vulnerablecode/pull/400
- Return the complete response in pagination view. CODE (https://gist.github.com/AmitGupta7580/c383c1e796d03f2f75d0e07b2624e2b0)
- Separate the `bulk_search` from `PackageViewSet` class. CODE (https://gist.github.com/AmitGupta7580/1124c73b9dbc5c6b6cb41a3f5fa1a73a). It works fine but it changes path from `/api/packages/bulk_search` to `/api/bulk_search`.
- Use custom template of SwaggerUI instead of using SpectacularSwaggerView (Import seprate scema.yaml for custom schema) (Reference: https://dev.to/matthewhegarty/swaggerui-inside-django-rest-framework-1c2p)

**Comment by AmitGupta7580** [comment]
@pombredanne @sbs2001 please give some suggestion which idea will be best or if you have any other idea please share.

**Comment by sbs2001** [comment]
Fixed via https://github.com/nexB/vulnerablecode/pull/542, api naming tracked at https://github.com/nexB/vulnerablecode/issues/543
