### ISSUE TITLE
DisallowedHost at / Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.

### ISSUE THREAD

**Issue by FrankensteinEvil0069** [nexB/vulnerablecode#448]
Please tell me what to do I have no clue at all <br> See this image please<br>
![disallowedhostimage](https://user-images.githubusercontent.com/60188502/115871462-36e83200-a45e-11eb-8165-a6e627b616aa.png)

**Comment by FrankensteinEvil0069** [comment]
I got the solution go to localhost:8080 or 127.0.0.1:8080

**Comment by zhy605420954** [comment]
> 127.0.0.1:8080

thank you
