### ISSUE TITLE
SECRET_KEY should never be commited.

### ISSUE THREAD

**Issue by singh1114** [nexB/vulnerablecode#46]
There is a secret key in the settings file. Secret key should never be committed to version control.

https://docs.djangoproject.com/en/2.1/ref/settings/#secret-key

https://github.com/nexB/vulnerablecode/blob/develop/vulnerablecode/settings.py#L22

**Comment by pombredanne** [comment]
@singh1114 good point, but this is not used in production at all, so this never might be an issue. @tdruez what would be the best practice though? a locally generated file?

**Comment by TG1999** [comment]
@pombredanne, @singh1114  I think we can store the secrets inside a file called secret.py and import in the file we want and then gitignore the secret.py file. And can tell in readme to user to setup a secret.py file inside their local clone and enter their config their .If approach looks good should I make a PR for it. :)
