### ISSUE TITLE
GitHubTagsAPI vs GitTagsAPI

### ISSUE THREAD

**Issue by Hritik14** [nexB/vulnerablecode#493]
Currently we are scraping Github for tags for VersionAPI
https://github.com/nexB/vulnerablecode/blob/e9943b014f5f07b970988f910b2aaebcec0a6e58/vulnerabilities/package_managers.py#L414-L466

Imo, we could have a `GitTagsAPI` looking at the GitDataSource's git filesystem and find out all the contained tags. This would avoid GitHub scraping without a proper API, plus it would work for all git repositories, regardless of being on GitHub.

Also, if we happen to move with GitHubTagsAPI, should we focus more on the `releases` part than the `tags` part ? Eg: https://api.github.com/repos/nexB/vulnerablecode/releases. This might not be favorable in all cases, I'd like some suggestions here.

**Comment by sbs2001** [comment]
@Hritik14  `GitHubTagsAPI` is used for getting tags without cloning the whole repo.

**Comment by Hritik14** [comment]
Agreed. We could have used `git ls-remote` to get the remote tags but after the addition of time travel (eec65ab) which needs the tag date, I don't think it would be possible now.

**Comment by pombredanne** [comment]
FWIW, probably too late ... if this helps:
https://github.com/nexB/scancode-toolkit/blob/3f7da81d6b207ac2b1d384defb83a5f2c82216f4/etc/scripts/licenses/synclic.py#L339 is a small utility function that I use to fetch tags using the GH api and then fetch a release archive from some repos.
