### ISSUE TITLE
Connect RTD

### ISSUE THREAD

**Issue by Hritik14** [nexB/vulnerablecode#498]
Soon enough we will start having RTD compatible docs. We should register on rtd and link vulnerablecode for now

**Comment by mjherzog** [comment]
Yes please. We need to push some basic documentation in order to "register" VulnerableCode on readthedocs.org and link it to vulnerablecode on GH.

**Comment by AyanSinhaMahapatra** [comment]
Yes! Also there's a sample RTD conf file here, https://github.com/nexB/skeleton/blob/main/.readthedocs.yml. 

Having activated the repository in RTD from admin and having this configuration file (and the build passes) should have a documentation hosted.

**Comment by AyanSinhaMahapatra** [comment]
Closing as this is completed.
