### ISSUE TITLE
Define basic models for storing essentials of vulnerabilities, packages and their relations

### ISSUE THREAD

**Issue by pombredanne** [nexB/vulnerablecode#5]
Here is a rough sketch:
![vulnerablecode-prototype-models](https://user-images.githubusercontent.com/675997/27684353-f70208d0-5cc9-11e7-9f65-158b8c57f57a.png)

**Comment by tdruez** [comment]
@pombredanne can you review the current models?
 https://github.com/nexB/vulnerablecode/blob/develop/app/vulncode_app/models.py
