### ISSUE TITLE
Add suggested fix in frontend

### ISSUE THREAD

**Issue by Hritik14** [nexB/vulnerablecode#524]
Our frontend currently shows the vulnerabilities a package is vulnerable to and is safe to. This data is important but not very much consumable by an end user. We should provide a suggested fix saying "Upgrade to <package>"
 
![image](https://user-images.githubusercontent.com/7457065/128866934-e1881432-cd5f-413d-97d6-738dd69aa7b2.png)

**Comment by Lawful2002** [comment]
@Hritik14 so we need to change "safe to" to "Upgrade to"?

**Comment by Hritik14** [comment]
@Lawful2002 not change but we should mention that which nearest package is safe to the "vulnerable to" vulnerabilities for the upgrade.

**Comment by pombredanne** [comment]
[The naming of cats is a difficult matter!](https://en.wikipedia.org/wiki/The_Naming_of_Cats)
As it stands we have not yet settled on a correct set of names. As I read https://github.com/CVEProject/cve-schema/issues/87  there are references to "affected", "unaffected" there. Not sure that's the standard, the related OSV spec uses other terms too https://docs.google.com/document/d/1sylBGNooKtf220RHQn1I8pZRmqXZQADDQ_TOABrKTpA/edit and https://github.com/ossf/osv-schema/blob/main/schema.md

**Comment by rsc** [comment]
For OSV we are still planning to stick with the more precise introduced and fixed. It should always be clear, given source access, which specific commits introduced and fixed a vulnerability. The unaffected/affected/unknown is more important for closed-source products.

/cc @oliverchang

**Comment by pombredanne** [comment]
@rsc Thanks! FYI:
- https://github.com/nexB/vulnerablecode/issues/540

**Comment by pombredanne** [comment]
Closed in favor of https://github.com/nexB/vulnerablecode/issues/1520 because the UI and models and API have evolved a lot since
