### ISSUE TITLE
Missing CONTRIBUTING File

### ISSUE THREAD

**Issue by blaemmle** [nexB/vulnerablecode#528]
Hello, 
i cant find a Contributing file, like it is provided for some other Repositories. e.g. [scancode-toolkit Contributing File](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
Could you please add one?
Thanks!

**Comment by Hritik14** [comment]
Hi @blaemmle 
Thank you for the report. The contributing file with some additional docs are on the way. They will be reflected here soon after we set up RTD (https://github.com/nexB/vulnerablecode/pull/527)

**Comment by pombredanne** [comment]
@blaemmle Good catch! I reckon you may be willing to contribute then?

**Comment by blaemmle** [comment]
Hi @pombredanne 
Probably not by myself. But i like to enable collegues to contribute and therefore i need the documentation to enable the process.

**Comment by sschuberth** [comment]
Like, can we simply reuse https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst?
