### ISSUE TITLE
Collect UVI database

### ISSUE THREAD

**Issue by pombredanne** [nexB/vulnerablecode#533]
See https://github.com/cloudsecurityalliance/uvi-database
It uses the https://github.com/google/osv#current-data-sources format

This has been renamed to https://github.com/cloudsecurityalliance/gsd-database

**Comment by ziadhany** [comment]
OSV format is still not supported yet.
https://osv.dev/list?q=&affected_only=true&page=1&ecosystem=UVI
https://osv-vulnerabilities.storage.googleapis.com/UVI/all.zip
@pombredanne

**Comment by pombredanne** [comment]
Closed as dupe in favor of https://github.com/nexB/vulnerablecode/issues/706
