### ISSUE TITLE
"cvssv3.1_qr" Qualitative Severity Rating Scale should say "Medium" instead of "MODERATE"

### ISSUE THREAD

**Issue by sschuberth** [nexB/vulnerablecode#550]
From the linked docs, its seems to me "MODERATE" should actually say "Medium":

https://github.com/nexB/vulnerablecode/blob/d7d3206ba1af98410b91655bfc96a147175eca75/vulnerabilities/severity_systems.py#L81-L82

**Comment by pombredanne** [comment]
@sschuberth thank you for your eagle eyes!
