### ISSUE TITLE
Missing VULCOIDS replacement implementation

### ISSUE THREAD

**Issue by Hritik14** [nexB/vulnerablecode#552]
The function to check if there is an existing ``VULCOID`` for an advisory with an alloted CVE is missing. We need to implement that i.e. effectively move ``VULCOID`` to from ``vulnerability_id`` to ``old_vulnerability_id``.
Further we need to decide where the VULCOID should be generated in the importer-improver design.

Via: https://github.com/nexB/vulnerablecode/wiki/WeeklyMeetings#meeting-on-thursday-2021-09-14-at-1400-utc

**Comment by pombredanne** [comment]
We have changed the design and now a VULCOID is always assigned together with one to many to Aliases (such as a CVE id). Fixed in #525
