### ISSUE TITLE
docker-compose up fails with exit code 127

### ISSUE THREAD

**Issue by arun-netsentries** [nexB/vulnerablecode#567]
docker-compose up fails with exit code 127 in Ubuntu EC2 instance

vulnerablecode_1  | ModuleNotFoundError: No module named 'vulnerablecode.wsgi'
vulnerablecode_1  | [2021-10-01 20:02:11 +0000] [17] [INFO] Worker exiting (pid: 17)
vulnerablecode_1  | [2021-10-01 20:02:11 +0000] [15] [INFO] Shutting down: Master
vulnerablecode_1  | [2021-10-01 20:02:11 +0000] [15] [INFO] Reason: Worker failed to boot.
vulnerablecode_1  | /bin/sh: 1: ./manage.py: not found
vulnerablecode_1  |

vulnerablecode_vulnerablecode_1 exited with code 127

**Comment by arun-netsentries** [comment]
Can someone please look in to this

**Comment by pombredanne** [comment]
@arun-netsentries Can you provide a bit more details? What exact sequence of commands did you issue?

**Comment by list4nestor** [comment]
Same issue in my side.
It comes from the "--clear" option that removes files widely, not only static files.
```
./manage.py collectstatic --no-input --clear
```

**Comment by pombredanne** [comment]
@list4nestor thank you ++ :bow: 
But --clear should not remove files widely... only the ones previously collected.
See https://docs.djangoproject.com/en/3.2/ref/contrib/staticfiles/#collectstatic

@tdruez this was carried from https://github.com/nexB/scancode.io/blob/64d6aa529a875d589e4ffccf4da7eea6190bb6b4/docker-compose.yml#L35  in https://github.com/nexB/vulnerablecode/blob/f9da8362f20219f78860f2bcd4443662f7480e62/docker-compose.yml#L13 ... any specific idea why it would fail here and not there?

**Comment by vbisserie** [comment]
I reproduce this problem. Here is a possible solution : https://github.com/nexB/vulnerablecode/pull/569

**Comment by sbs2001** [comment]
Closing this for now. @arun-netsentries  feel free to open this issue is still present
