### ISSUE TITLE
'404 not found' when import github

### ISSUE THREAD

**Issue by sify21** [nexB/vulnerablecode#575]
Currently import from github will report `404 not found` error in ` on following two lines:
https://github.com/nexB/vulnerablecode/blob/3388f885e220434a4c08476601ebc9853c89967a/vulnerabilities/package_managers.py#L313
https://github.com/nexB/vulnerablecode/blob/3388f885e220434a4c08476601ebc9853c89967a/vulnerabilities/package_managers.py#L351
Maybe we should ignore packages whose versions can't be retrieved.

**Comment by pombredanne** [comment]
>  Maybe we should ignore packages whose versions can't be retrieved.

This would be dangerous... the branch in https://github.com/nexB/vulnerablecode/pull/525 use a different approach and should alleviate these issues somewhat

**Comment by keshav-space** [comment]
This has been resolved, we return an empty list when we can't retrieve versions of a package.
Additionally, we no longer use asynchronous requests while collecting package versions from upstream.

The code for getting the package versions has been refactored and now resides in `fetchcode` under the `package_versions` module.
