### ISSUE TITLE
Wrong filters in `PackageSearchView`

### ISSUE THREAD

**Issue by Hritik14** [nexB/vulnerablecode#596]
See: https://github.com/nexB/vulnerablecode/blob/67fc00e5a8dbdf690f1c1b0d627da0d06322adb9/vulnerabilities/views.py#L74-L89

The filters are all wrong and probably need a rewrite
via: https://github.com/nexB/vulnerablecode/pull/525#discussion_r701219347

**Comment by naashit10** [comment]
I would like to work on this issue,I would appreciate that if somebody could help me to tackle this issue,

**Comment by pombredanne** [comment]
@naashit10 your first step is to check out, install and run VulnerableCode locally.
Which OS do you run?

**Comment by fatemajawad** [comment]
@pombredanne Sir mine is windows10 , what to do next

**Comment by pombredanne** [comment]
@fatemajawad You can try to install VulnerableCode either in a VM, with Docker or WSL2... we do not support Windows natively at this stage.

**Comment by melencholicmice** [comment]
Hello , I would like to work on this issue is this issue available ?
I have setuped the local development environment in my ubantu machine.

**Comment by Hritik14** [comment]
As the entire frontend has gone through a revamp. This issue might no longer be relevant. Can you confirm, @johnmhoran ?

**Comment by pombredanne** [comment]
I think this no longer applies as the code has been entirely refactored. I am closing this now

**Comment by mostafijur-rahman299** [comment]
I want to work on this issue Can anyone help me to deal with this issue. I already run this project on my linux machine by docker.
