### ISSUE TITLE
Collect NodeJS

### ISSUE THREAD

**Issue by haikoschol** [nexB/vulnerablecode#61]
https://github.com/nodejs/security-wg/tree/master/vuln

**Comment by pombredanne** [comment]
Note that we had also #101 but these seem complementary

**Comment by sbs2001** [comment]
https://github.com/nodejs/security-wg/tree/master/vuln/npm is collected from a more fresh source   in  our current npm importer. That leaves https://github.com/nodejs/security-wg/tree/master/vuln/core . Btw what should be package name for these?

**Comment by haikoschol** [comment]
@sbs2001 We discussed the same issue for Ruby (or Rust? or both? don't remember) and decided to leave out the upstream tarballs of the language toolchain itself for now.

Apart from the questions of what package-url attributes we should use for them, it's also unclear how a user of VulnerableCode would programmatically determine that they are using them. Meaning, if I download ruby-2.5.7.tar.gz and run `./configure && make && make install` (or whatever the equivalent is), how can a tool like scancode or ORT later detect that and query the VulnerableCode API accordingly?

I thnk we should remove this ticket (and similar ones) from the milestone.
