### ISSUE TITLE
Fix failing nix tests

### ISSUE THREAD

**Issue by Hritik14** [nexB/vulnerablecode#617]
Nix tests are failing. Probably some kind of dependency issue.
See more: https://github.com/nexB/vulnerablecode/runs/5094793358?check_suite_focus=true

**Comment by Hritik14** [comment]
@rolfschr, As you're our nix savior, can you please look into it ?

**Comment by rolfschr** [comment]
Hi @Hritik14, I can have a look into this. I see that the nix-related documentation has been removed from the readme. I guess that's ok. Still, could you please dig it up again an place it into `/etc/nix`? Thanks.

**Comment by Hritik14** [comment]
Thanks @rolfschr for responding. The nix docs have just been moved to RTD at https://vulnerablecode.readthedocs.io/en/latest/installation.html#using-nix as I couldn't do a quick and neat tl;dr to place on README.
We'll be glad to accept a tl;dr PR on readme if you'd like to.

**Comment by rolfschr** [comment]
@Hritik14 See #635.

**Comment by Hritik14** [comment]
@rolfschr Thank you so much! We have the green ticks now.
