### ISSUE TITLE
alpine_linux importer - improver migration

### ISSUE THREAD

**Issue by pombredanne** [nexB/vulnerablecode#620]

**Comment by pombredanne** [comment]
@TG1999 you wanted to help there... this could be a good one to start on may be?
@Hritik14 what do you think?

**Comment by pombredanne** [comment]
See also https://github.com/nexB/vulnerablecode/issues/499

**Comment by Hritik14** [comment]
@TG1999 That would be very nice of you to lend a hand :)
Also, have a look at https://github.com/nexB/vulnerablecode/issues/496
