### ISSUE TITLE
RTD link not working

### ISSUE THREAD

**Issue by keshav-space** [nexB/vulnerablecode#637]
Use complete URL for documentation link.
https://github.com/nexB/vulnerablecode/blob/4390b6aca872cbde378516199f143fa11e64bc5a/docs/source/contributing.rst#L21

Clicking on the `documentation` link doesn't take to: https://vulnerablecode.readthedocs.io/en/latest/
Instead redirects to -> https://github.com/nexB/vulnerablecode/blob/main/docs/source/vulnerablecode.readthedocs.io/en/latest

**Comment by Hritik14** [comment]
Thanks! This will be fixed in #631
