### ISSUE TITLE
License expression for OpenSSL Importer

### ISSUE THREAD

**Issue by keshav-space** [nexB/vulnerablecode#641]
Raised an issue with OpenSSL regarding the license expression for the vulnerability feeds
https://github.com/openssl/openssl/issues/17830

**Comment by pombredanne** [comment]
Per https://github.com/openssl/openssl/issues/17830#issuecomment-1061218095
> Apache 2

And this is handled in https://github.com/nexB/vulnerablecode/pull/648/files#diff-c0b6de70c5ad6d96de4f5eaf58c81d8af15abae52c44e14415dfeed8ff15ac81R46

So we can close this... and  @keshav-space do you mind to close this https://github.com/openssl/openssl/issues/17830 ?

**Comment by keshav-space** [comment]
Yeah, sure.
