### ISSUE TITLE
Values larger than 1/3 of a buffer page cannot be indexed.

### ISSUE THREAD

**Issue by TG1999** [nexB/vulnerablecode#650]
https://github.com/nexB/vulnerablecode/pull/632#discussion_r823700889

**Comment by TG1999** [comment]
A possible solution that I got https://stackoverflow.com/questions/41971217/values-larger-than-1-3-of-a-buffer-page-cannot-be-indexed-django-error, although this is Postgres specific not Django specific

**Comment by pombredanne** [comment]
#653 has been merged. Thanks!
