### ISSUE TITLE
Add support for CWE

### ISSUE THREAD

**Issue by pombredanne** [nexB/vulnerablecode#651]
We decided early to keep the data set we track as minimal... but adding CWE would be a great addition. This can be a fairly involved issue since many importers may need to be updated.

**Comment by ziadhany** [comment]
Can we use a library like this https://github.com/Julian-Nash/cwe to get a CWE by ID and add another JSON field in the model?

**Comment by Hritik14** [comment]
CWE could be used for categorization of vulnerabilities. Later on, we might be able to find a mapping between ``OWSAP top 10 -> CWE``, this can be used to prioritize vulnerabilities for the downstream.

To implement CWE (categorization) support a system similar to currently implemented [ScoringSystem](https://github.com/nexB/vulnerablecode/blob/67dda33e1e1926a380abb96023d757acfe45db78/vulnerabilities/severity_systems.py#L32) could be used.

_(via: )_

**Comment by ziadhany** [comment]
I think we have a compressed CSV file containing the fields of the desired Weaknesses related to CWE VIEW: Software Development.
https://cwe.mitre.org/data/definitions/699.html

https://cwe.mitre.org/data/csv/699.csv.zip
