### ISSUE TITLE
Collect gentoo

### ISSUE THREAD

**Issue by pombredanne** [nexB/vulnerablecode#69]
See GLSA example https://security.gentoo.org/glsa/201909-03
https://www.gentoo.org/support/security/ and feed at https://security.gentoo.org/subscribe

**Comment by sbs2001** [comment]
A better source to collect this data would be by cloning `git clone https://anongit.gentoo.org/git/data/glsa.git ` . @haikoschol ^

**Comment by sbs2001** [comment]
Is there an API for gentoo, from where I can get all versions of a gentoo package? I am stuck due to this.

**Comment by haikoschol** [comment]
@sbs2001 I don't know of an API for this. Have you asked someone from the Gentoo project? I'd say if we can't get all the information we need for collecting a particular source, then we don't.

**Comment by sbs2001** [comment]
https://packages.gentoo.org/ has the data in HTML(which we have agreed not to consume), but I haven't came across any sort of an API. 

>Have you asked someone from the Gentoo project?

I will try, @pombredanne ^ might know someone from the Gentoo foundation.

**Comment by sbs2001** [comment]
Here's a screenshot of  my recent email exchange with them: 
![email](https://user-images.githubusercontent.com/28975399/83320076-9dba9680-a261-11ea-89ff-e862e3f197e5.png)

Basically there's no API as of now, but they are planning to bring it.
