### ISSUE TITLE
Avoid using null on string-based fields such as CharField and TextField

### ISSUE THREAD

**Issue by tdruez** [nexB/vulnerablecode#692]
> Avoid using null on string-based fields such as CharField and TextField. If a string-based field has null=True, that means it has two possible values for “no data”: NULL, and the empty string.

For example https://github.com/nexB/vulnerablecode/blob/main/vulnerabilities/models.py#L64

**Comment by TG1999** [comment]
Thanks @tdruez for reporting this, adding reference here https://docs.djangoproject.com/en/dev/ref/models/fields/#null
