### ISSUE TITLE
Collect CVE from NVD

### ISSUE THREAD

**Issue by pombredanne** [nexB/vulnerablecode#71]
Of course :)
See also
- https://github.com/CVEProject/cvelist
- https://nvd.nist.gov/

**Comment by singh1114** [comment]
@pombredanne @haikoschol I can take on this. Can we discuss how we need to proceed with this?

This seems to be a good source of data: https://nvd.nist.gov/vuln/data-feeds

**Comment by pombredanne** [comment]
@singh1114 that would be awesome! let's bring it on the chat to discuss in details.
