### ISSUE TITLE
Collect vulnerabilities from GitHub

### ISSUE THREAD

**Issue by pombredanne** [nexB/vulnerablecode#74]
There are a few levels to consider:
1. GH provides some security feeds for their own GHE appliances
2. the projects hosted can publish their own feeds
3. a project dependencies can have vulnerabilities reported by GH

**Comment by pombredanne** [comment]
See https://github.com/gradle/gradle/security/advisories/GHSA-4cwg-f7qc-6r95 for an example

**Comment by sbs2001** [comment]
GitHub provides a GraphQL based API for these, we could collect this data from this API. As this API requires OAuth token, we need some mechanism to allow the user to specify  the token  (environmental variable). 

An example query at https://developer.github.com/v4/explorer/ to obtain this data would be :
```

query MyQuery {
  securityVulnerabilities(first: 10) {
    nodes {
      package {
        ecosystem
        name
      }
      vulnerableVersionRange
      advisory {
        description
        ghsaId
      }
    }
  }
}

```

**Comment by sbs2001** [comment]
Fixed by https://github.com/nexB/vulnerablecode/pull/204
