### ISSUE TITLE
Collect data from pypi API

### ISSUE THREAD

**Issue by TG1999** [nexB/vulnerablecode#758]
For example see this: https://pypi.org/pypi/Django/1.1.3/json

**Comment by johnmhoran** [comment]
I've drafted a gDoc describing the PyPi (and PyPA) advisory data, together with some suggestions -- and a number of questions -- re the collection process.  Please share your thoughts and suggestions.

[Strategy for collecting Python vulnerability data](https://docs.google.com/document/d/1tuJD4OJ4ItmZ98rLwX5Z4uJJZ0zf7zL2r4Y6DTNMJeA/edit?usp=sharing)

**Comment by TG1999** [comment]
@johnmhoran thanks for researching this, pypi API should be an improver and not an importer. This improver should take all the Pypi packages stored in vulnerablecode, get all the valid versions for a package, and validate that we don't store a version that's not in the releases coming from the API. Validate the package-version we have is actually vulnerable and collect the vulnerabilities for that particular package-version.

**Comment by johnmhoran** [comment]
Thank you @TG1999 .  👍
