### ISSUE TITLE
Collect Mozilla

### ISSUE THREAD

**Issue by pombredanne** [nexB/vulnerablecode#78]
See https://www.mozilla.org/en-US/security/known-vulnerabilities/

**Comment by pombredanne** [comment]
See also https://github.com/mozilla/foundation-security-advisories

**Comment by Ayushsunny** [comment]
Hellow @sbs2001 I would like to work on this issue

**Comment by prathamaror** [comment]
can I start working on this issue?

**Comment by prathamaror** [comment]
just want a thumbs up

**Comment by Hritik14** [comment]
The work was partial, this needs to be refactored and migrated to importer improver structure

**Comment by Hritik14** [comment]
@prathamaror Yes! Everyone is welcome to open a PR.

PS: You can open a draft PR to show us a progressive work. Also, we're available to chat on [gitter](https://gitter.im/aboutcode-org/vulnerablecode#)
