### ISSUE TITLE
Fix data migration problems

### ISSUE THREAD

**Issue by pombredanne** [nexB/vulnerablecode#818]
See https://github.com/nexB/vulnerablecode/pull/812
@TG1999 can you further elaborate on this?

**Comment by TG1999** [comment]
Reference ID | URL
-- | --
cpe:2.3:a:ibm:tklm:1.0:*:*:*:*:*:*:* | https://nvd.nist.gov/vuln/search/results?adv_search=true&isCpeNameSearch=true&query=cpe:2.3:a:ibm:tklm:1.0:*:*:*:*:*:*:*
-- | --
cpe:2.3:a:ibm:tklm:1.0:*:*:*:*:*:*:* | -

Previous data migration fix up cpe urls, but rerun of the importers somehow recreated CPEs with or without the URL and we ended up with duplicate cpe entries as before https://github.com/nexB/vulnerablecode/pull/785

**Comment by TG1999** [comment]
closed by #827

**Comment by pombredanne** [comment]
Based on a check the issue still exists:
```JSON
{
    "reference_url": "",
    "reference_id": "cpe:2.3:a:lxml:lxml:*:*:*:*:*:*:*:*",
    "scores": [],
    "url": ""
},
{
    "reference_url": "https://nvd.nist.gov/vuln/search/results?adv_search=true&isCpeNameSearch=true&query=cpe:2.3:a:lxml:lxml:*:*:*:*:*:*:*:*",
    "reference_id": "cpe:2.3:a:lxml:lxml:*:*:*:*:*:*:*:*",
    "scores": [],
    "url": "https://nvd.nist.gov/vuln/search/results?adv_search=true&isCpeNameSearch=true&query=cpe:2.3:a:lxml:lxml:*:*:*:*:*:*:*:*"
},
```

**Comment by pombredanne** [comment]
I suggest two approaches:
1. a code review to ensure this is fixed for good
2. an improver to further fix this issue and similar issues

**Comment by TG1999** [comment]
Fixed in https://github.com/nexB/vulnerablecode/commit/6d379d0028cf8673a5ab788985eb9a6baedbb8ab
