### ISSUE TITLE
Show vulnerability aliases in vulnerability search results list

### ISSUE THREAD

**Issue by JonoYang** [nexB/vulnerablecode#852]
Currently, the VULCOID is the only identifying key shown. I think it would be useful to show the aliases in addition to the VULCOIDs because the vulnerabilities are more known by their aliases than the VULCOIDs.

An idea of how it could look/work would be to do something like what we do in scancode.io's DiscoveredPackage list view, where only the first five Resources associated to a Package are shown, and the remaining Resources can be displayed by pressing the "Show x Resources" button. (https://github.com/nexB/scancode.io/blob/main/scanpipe/templates/scanpipe/package_list.html#L48)

![image](https://user-images.githubusercontent.com/6044800/185208907-f42a3299-596d-4660-886c-215c22f5328e.png)

**Comment by johnmhoran** [comment]
@JonoYang Thank you for helping me with the alias ordering.  My next task will be fixing the style of the toggled bulleted list, and then this issue will be implemented and pushed to PR #847.

**Comment by johnmhoran** [comment]
@JonoYang I was able to fix the toggled bulleted list style problem by simply moving my custom CSS `class="is-clipped-list"` from the `<td>` (which the JS was stripping of its class) to the parent `<tr>`.  Magic.

**Comment by johnmhoran** [comment]
Sorted alias column has been implemented, committed and pushed to https://github.com/nexB/vulnerablecode/pull/847

**Comment by johnmhoran** [comment]
This was addressed several days ago and pushed to https://github.com/nexB/vulnerablecode/pull/847.
