### ISSUE TITLE
Add minimal About page/documentation including ToS

### ISSUE THREAD

**Issue by pombredanne** [nexB/vulnerablecode#856]
This would be needed for going live.

- [x] This should be an `About` in the top bar just left of the version and that would display simple text like the about in https://github.com/nexb/vulnerablecode  
- [x] The about text should also provide an email to ask for an API key to access the API for https://github.com/nexB/vulnerablecode/issues/460#issuecomment-1219653083
- [x] #923

**Comment by pombredanne** [comment]
The about text should also provide an email to ask for an API key to access the API for https://github.com/nexB/vulnerablecode/issues/460#issuecomment-1219653083

**Comment by johnmhoran** [comment]
About info added 1 or 2 days ago in push to https://github.com/nexB/vulnerablecode/pull/847.

Re (1) `about text should also provide an email to ask for an API key to access the API` and (2) `We also need minimal contact info or it could be in the footer`, I'll implement as soon as someone provides the desired text, email address, contact info etc.

**Comment by johnmhoran** [comment]
@pombredanne   Re the About text and the need for API key instructions and minimal contact info, this is what the new About currently looks like when the user hovers over `About` in the navbar (as discussed, this comes from the upper-right corner of the GH README):  


![image](https://user-images.githubusercontent.com/11096678/186504147-fbb357e4-92c2-4a1f-b745-3cda1a39985c.png)

**Comment by pombredanne** [comment]
This About is fine. Thanks!

**Comment by mjherzog** [comment]
We need to define the TOS and criteria for providing API access before not after.

**Comment by pombredanne** [comment]
See https://github.com/nexB/vulnerablecode/issues/923 for details and follow up.

**Comment by pombredanne** [comment]
I suggest this footer:

> VulnerableCode is free software by nexB Inc. and others | Source code license: Apache-2.0 | Data license: CC-BY-SA-4.0 | Terms of Service


Terms of service should link to a file saved in this repo and we should ensure that the ToS tells clearly that they apply to nexB-hosted VulnerableCode instances.

**Comment by johnmhoran** [comment]
Addressed in #933
