### ISSUE TITLE
Error 500 with this search packages/search?purl=pkg:pypi/lxml@4.9.0

### ISSUE THREAD

**Issue by pombredanne** [nexB/vulnerablecode#857]

**Comment by johnmhoran** [comment]
@pombredanne FWIW 

- `http://127.0.0.1:8001/packages/search?purl=pkg:pypi/lxml@4.9.0` on my local branch/DB also throws a 500 error.

- if I simply search for `pkg:pypi/lxml@4.9.0` this works (and generates the URL `http://127.0.0.1:8001/packages/search?type=&name=pkg%3Apypi%2Flxml%404.9.0&template=index`).  
![image](https://user-images.githubusercontent.com/11096678/185681139-d8832abd-b561-4be2-bbda-fb3154c2ac8f.png)

**Comment by johnmhoran** [comment]
@pombredanne Is this still a live issue?  Please see my 8/19/22 comment above.

**Comment by TG1999** [comment]
@johnmhoran thanks this is completed now.
