### ISSUE TITLE
Opening sentence of Importer Overview should be improved

### ISSUE THREAD

**Issue by DennisClark** [nexB/vulnerablecode#886]
The opening sentence at https://vulnerablecode.readthedocs.io/en/latest/reference_importer_overview.html#importer-overview 
is difficult to understand and reads: 

Importers are responsible to scrape vulnerability data from various data sources without creating a complete relational model between vulnerabilites, their fixes and store them in a structured fashion.

I would like to suggest something like: 

Importers are responsible for scraping vulnerability data such as vulnerabilities and their fixes and for storing the scraped information in a structured fashion. The structured data created by the importer then provides input to an importer which is responsible for creating a relational model for vulnerabilities, affected packages and fixed packages.

And perhaps a link to the improver section would be good here, but maybe not necessary.

**Comment by johnmhoran** [comment]
Thanks @DennisClark -- I've made your changes and a few additional minor edits.

**Comment by johnmhoran** [comment]
Done and closing.
