### ISSUE TITLE
Use of a slang expressions should be avoided in readthedocs

### ISSUE THREAD

**Issue by DennisClark** [nexB/vulnerablecode#887]
The unexpected term “sausage” can be found at 
https://vulnerablecode.readthedocs.io/en/latest/tutorial_add_new_importer.html
and we should avoid terms that could be mis-interpreted

`A lot of internal sausage about importers could be found inside`

There is a similar problem at 
https://vulnerablecode.readthedocs.io/en/latest/tutorial_add_new_improver.html 

perhaps `discussion` would be a better word here than `sausage`.

**Comment by johnmhoran** [comment]
Done.

**Comment by johnmhoran** [comment]
Done and closing.
