### ISSUE TITLE
Replace instances of "is supposed to" with "is intended to" 

### ISSUE THREAD

**Issue by DennisClark** [nexB/vulnerablecode#888]
The use of the expression "is supposed to" in several places in readthedocs is odd and perhaps a bit misleading due to the usual connotations  of "supposed to".  For example, see 
https://vulnerablecode.readthedocs.io/en/latest/tutorial_add_new_improver.html#implement-the-interesting-advisories-property

`This property is supposed to return a QuerySet of Advisory...` 

would be much better as 

`This property is intended to return a QuerySet of Advisory...`

It would be nice to improve all instances of this expression in readthedocs.

**Comment by johnmhoran** [comment]
I've fixed all instances of `supposed to` in the RTD.

**Comment by johnmhoran** [comment]
Done and closing.
