### ISSUE TITLE
Remove duplicate fields from API that have same data

### ISSUE THREAD

**Issue by TG1999** [nexB/vulnerablecode#892]
currently `reference_url` and `url` have same data and `unresolved_vulnerabilities`  and  `affected_by_vulnerabilities` have same data. We need to drop one of these for both before release

**Comment by pombredanne** [comment]
There is a story to write down in the doc to explain that one of the duplicated field name is deprecated and will be removed in the next version.

**Comment by pombredanne** [comment]
I add a note in the changelog for now with https://github.com/nexB/vulnerablecode/pull/909/files#diff-2c623f3c6a917be56c59d43279244996836262cb1e12d9d0786c9c49eef6b43cR49

**Comment by uzaxirr** [comment]
I would like to work on this, can you specify the endpoint from which these fields have to be dropped.

Also can you state which field i have to drop from the above pair

**Comment by pombredanne** [comment]
@uzaxirr you would have to do a bit of research based on link above and the dates of the comments here. There is no other as we did not keep the details here. You can check the log of the affected files.

**Comment by TG1999** [comment]
@uzaxirr we had added duplicate fields because some of the early adopters still use the old API fields, we need to confirm from them before going ahead.

**Comment by TG1999** [comment]
fixed by #1222
