### ISSUE TITLE
Typo in vulnerability view

### ISSUE THREAD

**Issue by TG1999** [nexB/vulnerablecode#903]
![Screenshot from 2022-09-06 18-57-53](https://user-images.githubusercontent.com/34160672/188661254-98e5630d-1b51-45e4-87b4-56008059627c.png)
It should be `Fixed By Packages` and not `Fixed Packages`

**Comment by johnmhoran** [comment]
Thank you @TG1999 .  FYI I based this on the original code: 

![image](https://user-images.githubusercontent.com/11096678/188673897-1e2b68ad-20b2-419e-b20c-1082c5cde50b.png)

**Comment by pombredanne** [comment]
Fixed with #894
