### ISSUE TITLE
Collect Pyup safety DB

### ISSUE THREAD

**Issue by pombredanne** [nexB/vulnerablecode#91]
See https://pypi.org/project/safety/ and https://github.com/pyupio/safety-db
To discuss with pyup @jayfk since the license is a a non FOSS CC-BY-NC-4.0

**Comment by pombredanne** [comment]
@jayfk @Jwomers ping... what is happening to safetydb? any plan for updates and an alternative license?

**Comment by sbs2001** [comment]
https://github.com/nexB/vulnerablecode/pull/153 imports safety-db, so this can be closed
