### ISSUE TITLE
We need minimal contact info or it could be in the footer

### ISSUE THREAD

**Issue by TG1999** [nexB/vulnerablecode#923]
Add contact info for getting API keys

Here is a simple thing to add to the About pop-up and here is a proposed About update:

> A free and open vulnerabilities database and the packages they impact. And the tools to aggregate and correlate these vulnerabilities.
> 
> - Sponsored by NLnet https://nlnet.nl/project/vulnerabilitydatabase/ for https://www.aboutcode.org/
> - Chat at https://gitter.im/aboutcode-org/vulnerablecode
> - Docs at https://vulnerablecode.readthedocs.org/
> - Source code and issues at https://github.com/nexB/vulnerablecode
> 
> If you want to try the JSON REST API, please send a note to info@nexb.com to request an API key for testing.

**Comment by johnmhoran** [comment]
Addressed in PR #933
