### ISSUE TITLE
Enhancement: Make dates more visible and usable in VCIO

### ISSUE THREAD

**Issue by DennisClark** [nexB/vulnerablecode#924]
As we step back a bit and look at our newest release of vulnerablecode.io  I think it is time to start thinking about how users can get the most out of the data.  I believe that it would be a very useful and valuable use case for a user to be able to search VCIO for Vulnerabilities that have been created or modified within the last day, 7 days, 30 days, or similar, and then to see the pertinent dates in the list of returned results and in the details. 

I found these date fields in models.py: 
date_published
date_collected
date_improved 
and there may be others that I missed.  
These dates are actually quite valuable information, but I don't see them in the UI (unless I'm missing something). 

It also seems to me that the database should really have, on every table, the equivalent of the following: 
date_created
date_modified
which would simply be the date of the create/modify in our DB. 

This idea should be discussed.  I think we could start by making the already existing fields visible (or more visible) in the UI, and then we might look into searching by, filtering by, and ordering by selected dates.

**Comment by pombredanne** [comment]
I would like to consider this in the context of #1007 and also possibly using something like https://github.com/justquick/django-activity-stream to store events. The reason is that implementing dates implies quite a few updates and this more ambitious approach may not be much more work.

**Comment by DennisClark** [comment]
Note: we are trying to make the dates consistent across aboutcode projects.

**Comment by TG1999** [comment]
Ater all discussion PR https://github.com/nexB/vulnerablecode/pull/1310 is ready for review now
