### ISSUE TITLE
AdvisoryData().to_dict() throws error re AffectedPackage object

### ISSUE THREAD

**Issue by johnmhoran** [nexB/vulnerablecode#930]
While trying to print the output of a simple test, where the output was a single `AdvisoryData()` object, I received this error: 

```
FAILED vulnerabilities/tests/test_archlinux.py::test_parse_advisory - AttributeError: 'AffectedPackage' object has no attribute 'to_dict'
```

This is the current `to_dict()` method for `AdvisoryData()`:

```
    def to_dict(self):
        return {
            "aliases": self.aliases,
            "summary": self.summary,
            "affected_packages": [pkg.to_dict() for pkg in self.affected_packages],
            "references": [ref.to_dict() for ref in self.references],
            "date_published": self.date_published.isoformat() if self.date_published else None,
        }
```

**Comment by johnmhoran** [comment]
More context: I'm working on migrating `archlinux.py`.  Inside my newly-named `parse_advisory()` method, I create and return a list named `advisories` containing 1+ `AdvisoryData()` objects.  Just before I return, I run this simple print that is triggered by my test:

```
        for apple in advisories:
                pprint.pprint(apple.to_dict())
```

**Comment by TG1999** [comment]
@johnmhoran the `AffectedPackage` https://github.com/nexB/vulnerablecode/blob/main/vulnerabilities/utils.py#L41 you are getting is from `nearest_patched_package` https://github.com/nexB/vulnerablecode/blob/main/vulnerabilities/utils.py#L160 , which is different from the `AffectedPackage` https://github.com/nexB/vulnerablecode/blob/main/vulnerabilities/importer.py#L121  in `importer.py` https://github.com/nexB/vulnerablecode/blob/main/vulnerabilities/importer.py, please look at `AdvisoryData` https://github.com/nexB/vulnerablecode/blob/main/vulnerabilities/importer.py#L224  class in `importer.py` to know which AffectedPackage class has been used.

**Comment by TG1999** [comment]
@johnmhoran can we close this now?

**Comment by johnmhoran** [comment]
@TG1999 I have no idea, have not been following this issue, have not encountered anything like this in the recent past.  Perhaps the best approach is to close this issue and if I encounter the same or a similar problem I can open a new issue.

**Comment by johnmhoran** [comment]
This appears to have been resolved.  Closing now, will reopen/open new issue if need be.
