### ISSUE TITLE
archlinux importer: package url is wrong according to purl-spec

### ISSUE THREAD

**Issue by sify21** [nexB/vulnerablecode#941]
Currently purl from archlinux importer is formatted as `pkg:pacman/archlinux/{name}@{version}`
 
But according to the official docs: https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst

`alpm` should be used as `type` field instead of `pacman`. (Actually there is no `pacman` type).
`arch`, `arch32`, `archarm`, `manjaro` or `msys` should be used as `namespace` field instead of `archlinux`.

> alpm
> ----
> ``alpm`` for Arch Linux and other users of the libalpm/pacman package manager.
> 
> - There is no default package repository: this should be implied either from
>   the ``distro`` qualifiers key  or using a repository base url as
>   ``repository_url`` qualifiers key.
> - The ``namespace`` is the vendor such as ``arch``, ``arch32``, ``archarm``,
>   ``manjaro`` or ``msys``. It is not case sensitive and must be lowercased.
> - The ``name`` is the package name. It is not case sensitive and must be lowercased.
> - The ``version`` is the version of the package as specified in [`vercmp(8)`](https://man.archlinux.org/man/vercmp.8#DESCRIPTION) as part of alpm.
> - The ``arch`` is the qualifiers key for a package architecture.
> - Examples::
> 
>       pkg:alpm/arch/pacman@6.0.1-1?arch=x86_64
>       pkg:alpm/arch/python-pip@21.0-1?arch=any
>       pkg:alpm/arch/containers-common@1:0.47.4-4?arch=x86_64

**Comment by TG1999** [comment]
@sify21 thanks for pointing this, this is under progress in https://github.com/nexB/vulnerablecode/pull/935

**Comment by TG1999** [comment]
@sify21 thanks for raising this, this is now fixed. I am closing this now.
