### ISSUE TITLE
Need to identify license for archlinux vulnerability data

### ISSUE THREAD

**Issue by johnmhoran** [nexB/vulnerablecode#946]
I've not yet been able to identify the license (if any) under which we can use the archlinux vulnerability data.

**Comment by johnmhoran** [comment]
Additional research suggests that this correctly reflects the data licensing:

```
class ArchlinuxImporter(Importer):
    url = "https://security.archlinux.org/json"
    spdx_license_expression = "MIT"
    license_url = "https://github.com/archlinux/arch-security-tracker/blob/master/LICENSE"
```

**Comment by TG1999** [comment]
The importer is now merged closing this now.
