### ISSUE TITLE
Add API item to VulnerableCode.io banner

### ISSUE THREAD

**Issue by mjherzog** [nexB/vulnerablecode#947]
The instructions for requesting an API key need to be more prominent. 
We should add an API item to the banner after Documentation. When you select it we should provide the following text:

If you want to try the JSON REST API for VulnerableCode.io , please send an email to [info@nexb.com](mailto:info@nexb.com) with "VulnerableCode API Key" in the email title. API access is limited to a maximum of 1000 package-versions per request."

And remove the text from the bottom of the About text.

**Comment by TG1999** [comment]
This is now completed in the UI closing it
