### ISSUE TITLE
Plan for merging VulnTotal PRs

### ISSUE THREAD

**Issue by keshav-space** [nexB/vulnerablecode#950]
This is the order in which we should merge these PRs

- [x] https://github.com/nexB/vulnerablecode/pull/788
- [x] https://github.com/nexB/vulnerablecode/pull/789
- [x] https://github.com/nexB/vulnerablecode/pull/804
- [x] https://github.com/nexB/vulnerablecode/pull/829
- [x] https://github.com/nexB/vulnerablecode/pull/842
- [x] https://github.com/nexB/vulnerablecode/pull/883
- [x] https://github.com/nexB/vulnerablecode/pull/832
- [x] https://github.com/nexB/vulnerablecode/pull/801
- [x] https://github.com/nexB/vulnerablecode/pull/901

**Comment by pombredanne** [comment]
@keshav-space All merged in https://github.com/nexB/vulnerablecode/pull/1009
I applied a few refinements:
- use smaller test files for snyk
- mark network tests as such. Also use a faster NuGet endpoint
- various minor refactoring
- use standard license notice headers

Ready for your review

**Comment by pombredanne** [comment]
Closing since the plan was "applied"
