### ISSUE TITLE
Update VulnerableCode Overview on ReadtheDocs

### ISSUE THREAD

**Issue by mjherzog** [nexB/vulnerablecode#963]
I drafted an update for the Overview page at https://vulnerablecode.readthedocs.io/en/latest/introduction.html. 
I drafted the text in Word and converted it to the .rst format file that is attached (I used an online conversion tool - https://www.vertopal.com/), but GH will not accept a .rst file for upload.
I attached a copy of the .rst file with a .txt file extension and a copy of the .docx file.
Please replace the current content with this updated version.
[VulnerableCode Overview.docx](https://github.com/nexB/vulnerablecode/files/9825369/VulnerableCode.Overview.docx)
[VulnerableCode Overview.txt](https://github.com/nexB/vulnerablecode/files/9825379/VulnerableCode.Overview.txt)

**Comment by johnmhoran** [comment]
@mjherzog Please note that the bottom of the overview .rst (`introduction.rst`) contains this attribution, which seems out of place.

```
.. Some of this documentation is borrowed from the metaflow documentation and is also
   under Apache-2.0
.. Copyright (c) Netflix
```

I don't know the exact source of this attribution or the related text.  Do we want/need to keep this?

**Comment by mjherzog** [comment]
@johnmhoran The updated page looks good except that I mistakenly published the last paragraph in italics. It should just be regular text.
I do not see where the attribution for Netflix appears, but we do not want it for VulnerableCode. It is most likely some carryover from ScanCode.io.

**Comment by mjherzog** [comment]
Closed as completed.
