### ISSUE TITLE
Add API documentation for VulnerableCode.io

### ISSUE THREAD

**Issue by mjherzog** [nexB/vulnerablecode#976]
We need to add basic API usage documentation for VulnerableCode.io. This should probably be added in the Reference section and then we can provide a direct link to the new section from VCIO. My assumption is that this documentation can be generated in the same way as we handle API documentation for SCIO

**Comment by TG1999** [comment]
https://www.django-rest-framework.org/topics/documenting-your-api/

**Comment by TG1999** [comment]
We were using drf-spectacular previously, but it's not been used anymore because of https://github.com/tfranzel/drf-spectacular/issues/389

**Comment by pombredanne** [comment]
This is completed. Closing. See https://public.vulnerablecode.io/api/docs/
