### ISSUE TITLE
Add documentation for VC database fields

### ISSUE THREAD

**Issue by mjherzog** [nexB/vulnerablecode#977]
We need to add Reference documentation for the VulnerableCode database fields. Perhaps we can regenerate the diagrams that @johnmhoran created about a month ago (copies attached). We may need to figure out how to create them in a narrower width format because is it annoying to scroll for this type of diagram - see https://vulnerablecode.readthedocs.io/en/latest/reference_framework_overview.html.
This may be the time to widen our RTD page format.

**Comment by mjherzog** [comment]
![VC_DB_core_diagram](https://user-images.githubusercontent.com/4853767/197075504-d4e432c6-4e67-4ad5-98c4-ee47fff09d93.png)
![VC_DB_diagram](https://user-images.githubusercontent.com/4853767/197075507-034f2fd4-dcdc-4d1e-93b7-00d594e25a4f.png)

**Comment by pombredanne** [comment]
As an example we generate models docs in SCIO here https://scancodeio.readthedocs.io/en/latest/data-models.html

**Comment by mjherzog** [comment]
@johnmhoran We need to widen this page in the RTD as you did for the Audit/Analysis/SPATS RTD. There are already 2 tables there that you cannot read in portrait-only format so we need landscape even before considering how to display a DB diagram. It would be best if you can just widen the page for now since we have not polled the team on changing look & feel overall.

**Comment by johnmhoran** [comment]
Will do @mjherzog .

**Comment by johnmhoran** [comment]
@mjherzog I've added some simple CSS and folder structure etc. and the vulnerablecode RTD page now has the wide look of the other RTD.  The latter has much more CSS for various widgets, dropdowns, a navbar etc. and I'm not proposing we add all of that to the vulnerablecode RTD.  However, before I commit and push I could show you what we now have locally and get any immediate additional feedback you might have.  Comparisons pasted below.  How would you like to proceed?

Before:

![image](https://github.com/nexB/vulnerablecode/assets/11096678/f5190737-106b-482b-9462-ede913d86ba6)

After:

![image](https://github.com/nexB/vulnerablecode/assets/11096678/549c7279-6c24-4f03-9797-a8c62f1c9920)

**Comment by mjherzog** [comment]
Please proceed with the width change for now. I think that we will want to make landscape and a default and add some or all of the other features from the private RTDs, but we need to engage a broader group who are interested in our doc style. I am guessing Ayan, Dennis, Thomas and Philippe, but we need to open the floor to all nexB people and likely the AboutCode community people who are interested.

**Comment by johnmhoran** [comment]
OK.

**Comment by johnmhoran** [comment]
@mjherzog I've reviewed my 2022 notes, created a new test branch, loaded/installed various packages including graphviz, and my initial simple command produced this -- a start.

![test-vcio-db-2023-11-20-01](https://github.com/nexB/vulnerablecode/assets/11096678/6f00f442-bf5a-453e-ab65-5cbbde0d6169)

**Comment by mjherzog** [comment]
@johnmhoran Thank you for the diagram! It seems from top-down that there are two major chunks here:
- The application data which includes everything from left-to-right including Advisory
- The admin data which includes everything from left-to-right starting with Token Proxy
So it would be nice to somehow split this into 2 diagrams along those lines.

**Comment by johnmhoran** [comment]
@mjherzog Here's an example of the application group:

![test-vcio-db-application-2023-11-21-01](https://github.com/nexB/vulnerablecode/assets/11096678/0778a875-a6da-4300-8df9-a0e8c42ac9f5)

and the admin group:

![test-vcio-db-admin-2023-11-21-01](https://github.com/nexB/vulnerablecode/assets/11096678/7ef2fd3d-d332-49c0-8246-7da8d8a37fcd)

**Comment by mjherzog** [comment]
We should add these to the VulnerableCode RTD documentation - presumably a new sub-section in the Reference section.

**Comment by johnmhoran** [comment]
@mjherzog I've added a new `Model Overview` page to the vulnerablecode RTD containing the application and admin graph diagrams generated with Graphviz.  You can see the initial draft here: 

https://vulnerablecode--1350.org.readthedocs.build/en/1350/reference_model_overview.html

**Comment by mjherzog** [comment]
The diagrams look good. We will need a process to keep them in sync with Model changes over time, but closing this Issue because it has been completed.
