### ISSUE TITLE
UI bug in severity table

### ISSUE THREAD

**Issue by TG1999** [nexB/vulnerablecode#982]
![Screenshot from 2022-10-26 23-04-52](https://user-images.githubusercontent.com/34160672/198096712-79ac4c73-6078-4cce-840b-bee0694b5fe0.png)

**Comment by johnmhoran** [comment]
Thanks @TG1999.   However, you don't describe the bug -- what is it, and what is the expected behavior?

**Comment by TG1999** [comment]
@johnmhoran please look at the severity table in the above screenshot, it goes outside the box, same bug as this https://github.com/nexB/vulnerablecode/issues/916

**Comment by johnmhoran** [comment]
Thank you @TG1999 -- I see it now.  🙂

**Comment by TG1999** [comment]
Done in https://github.com/nexB/vulnerablecode/pull/983, thanks @johnmhoran
